(ns cljc.java-time.zone-id (:refer-clojure :exclude [get range format min max next name resolve short]) (:require [cljc.java-time.extn.calendar-awareness] [java.time :refer [ZoneId]]))
(def short-ids (goog.object/get java.time.ZoneId "SHORT_IDS"))
(clojure.core/defn get-available-zone-ids {:arglists (quote ([]))} (^java.util.Set [] (js-invoke java.time.ZoneId "getAvailableZoneIds")))
(clojure.core/defn of {:arglists (quote (["java.lang.String"] ["java.lang.String" "java.util.Map"]))} (^js/JSJoda.ZoneId [^java.lang.String java-lang-String4592] (js-invoke java.time.ZoneId "of" java-lang-String4592)) (^js/JSJoda.ZoneId [^java.lang.String java-lang-String4593 ^java.util.Map java-util-Map4594] (js-invoke java.time.ZoneId "of" java-lang-String4593 java-util-Map4594)))
(clojure.core/defn of-offset {:arglists (quote (["java.lang.String" "java.time.ZoneOffset"]))} (^js/JSJoda.ZoneId [^java.lang.String java-lang-String4595 ^js/JSJoda.ZoneOffset java-time-ZoneOffset4596] (js-invoke java.time.ZoneId "ofOffset" java-lang-String4595 java-time-ZoneOffset4596)))
(clojure.core/defn to-string {:arglists (quote (["java.time.ZoneId"]))} (^java.lang.String [^js/JSJoda.ZoneId this4597] (.toString this4597)))
(clojure.core/defn get-display-name {:arglists (quote (["java.time.ZoneId" "java.time.format.TextStyle" "java.util.Locale"]))} (^java.lang.String [^js/JSJoda.ZoneId this4598 ^js/JSJoda.TextStyle java-time-format-TextStyle4599 ^java.util.Locale java-util-Locale4600] (.displayName this4598 java-time-format-TextStyle4599 java-util-Locale4600)))
(clojure.core/defn get-rules {:arglists (quote (["java.time.ZoneId"]))} (^js/JSJoda.ZoneRules [^js/JSJoda.ZoneId this4601] (.rules this4601)))
(clojure.core/defn get-id {:arglists (quote (["java.time.ZoneId"]))} (^java.lang.String [^js/JSJoda.ZoneId this4602] (.id this4602)))
(clojure.core/defn normalized {:arglists (quote (["java.time.ZoneId"]))} (^js/JSJoda.ZoneId [^js/JSJoda.ZoneId this4603] (.normalized this4603)))
(clojure.core/defn system-default {:arglists (quote ([]))} (^js/JSJoda.ZoneId [] (js-invoke java.time.ZoneId "systemDefault")))
(clojure.core/defn from {:arglists (quote (["java.time.temporal.TemporalAccessor"]))} (^js/JSJoda.ZoneId [^js/JSJoda.TemporalAccessor java-time-temporal-TemporalAccessor4604] (js-invoke java.time.ZoneId "from" java-time-temporal-TemporalAccessor4604)))
(clojure.core/defn hash-code {:arglists (quote (["java.time.ZoneId"]))} (^int [^js/JSJoda.ZoneId this4605] (.hashCode this4605)))
(clojure.core/defn equals {:arglists (quote (["java.time.ZoneId" "java.lang.Object"]))} (^boolean [^js/JSJoda.ZoneId this4606 ^java.lang.Object java-lang-Object4607] (.equals this4606 java-lang-Object4607)))
