(ns cljc.java-time.day-of-week (:refer-clojure :exclude [get range format min max next name resolve short]) (:require [cljc.java-time.extn.calendar-awareness]) (:import [java.time DayOfWeek]))
(def saturday java.time.DayOfWeek/SATURDAY)
(def thursday java.time.DayOfWeek/THURSDAY)
(def friday java.time.DayOfWeek/FRIDAY)
(def wednesday java.time.DayOfWeek/WEDNESDAY)
(def sunday java.time.DayOfWeek/SUNDAY)
(def monday java.time.DayOfWeek/MONDAY)
(def tuesday java.time.DayOfWeek/TUESDAY)
(clojure.core/defn range {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalField"]))} (^java.time.temporal.ValueRange [^java.time.DayOfWeek this26314 ^java.time.temporal.TemporalField java-time-temporal-TemporalField26315] (.range this26314 java-time-temporal-TemporalField26315)))
(clojure.core/defn values {:arglists (quote ([]))} (^"java.lang.Class" [] (java.time.DayOfWeek/values)))
(clojure.core/defn value-of {:arglists (quote (["java.lang.String"] ["java.lang.Class" "java.lang.String"]))} (^java.time.DayOfWeek [^java.lang.String java-lang-String26316] (java.time.DayOfWeek/valueOf java-lang-String26316)) (^java.lang.Enum [^java.lang.Class java-lang-Class26317 ^java.lang.String java-lang-String26318] (java.time.DayOfWeek/valueOf java-lang-Class26317 java-lang-String26318)))
(clojure.core/defn of {:arglists (quote (["int"]))} (^java.time.DayOfWeek [^java.lang.Integer int26319] (java.time.DayOfWeek/of int26319)))
(clojure.core/defn ordinal {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.Integer [^java.time.DayOfWeek this26320] (.ordinal this26320)))
(clojure.core/defn plus {:arglists (quote (["java.time.DayOfWeek" "long"]))} (^java.time.DayOfWeek [^java.time.DayOfWeek this26321 ^long long26322] (.plus this26321 long26322)))
(clojure.core/defn query {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalQuery"]))} (^java.lang.Object [^java.time.DayOfWeek this26323 ^java.time.temporal.TemporalQuery java-time-temporal-TemporalQuery26324] (.query this26323 java-time-temporal-TemporalQuery26324)))
(clojure.core/defn to-string {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.String [^java.time.DayOfWeek this26325] (.toString this26325)))
(clojure.core/defn minus {:arglists (quote (["java.time.DayOfWeek" "long"]))} (^java.time.DayOfWeek [^java.time.DayOfWeek this26326 ^long long26327] (.minus this26326 long26327)))
(clojure.core/defn get-display-name {:arglists (quote (["java.time.DayOfWeek" "java.time.format.TextStyle" "java.util.Locale"]))} (^java.lang.String [^java.time.DayOfWeek this26328 ^java.time.format.TextStyle java-time-format-TextStyle26329 ^java.util.Locale java-util-Locale26330] (.getDisplayName this26328 java-time-format-TextStyle26329 java-util-Locale26330)))
(clojure.core/defn get-value {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.Integer [^java.time.DayOfWeek this26331] (.getValue this26331)))
(clojure.core/defn name {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.String [^java.time.DayOfWeek this26332] (.name this26332)))
(clojure.core/defn get-long {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalField"]))} (^long [^java.time.DayOfWeek this26333 ^java.time.temporal.TemporalField java-time-temporal-TemporalField26334] (.getLong this26333 java-time-temporal-TemporalField26334)))
(clojure.core/defn get-declaring-class {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.Class [^java.time.DayOfWeek this26335] (.getDeclaringClass this26335)))
(clojure.core/defn from {:arglists (quote (["java.time.temporal.TemporalAccessor"]))} (^java.time.DayOfWeek [^java.time.temporal.TemporalAccessor java-time-temporal-TemporalAccessor26336] (java.time.DayOfWeek/from java-time-temporal-TemporalAccessor26336)))
(clojure.core/defn is-supported {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalField"]))} (^java.lang.Boolean [^java.time.DayOfWeek this26337 ^java.time.temporal.TemporalField java-time-temporal-TemporalField26338] (.isSupported this26337 java-time-temporal-TemporalField26338)))
(clojure.core/defn hash-code {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.Integer [^java.time.DayOfWeek this26339] (.hashCode this26339)))
(clojure.core/defn adjust-into {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.Temporal"]))} (^java.time.temporal.Temporal [^java.time.DayOfWeek this26340 ^java.time.temporal.Temporal java-time-temporal-Temporal26341] (.adjustInto this26340 java-time-temporal-Temporal26341)))
(clojure.core/defn compare-to {:arglists (quote (["java.time.DayOfWeek" "java.lang.Enum"]))} (^java.lang.Integer [^java.time.DayOfWeek this26342 ^java.lang.Enum java-lang-Enum26343] (.compareTo this26342 java-lang-Enum26343)))
(clojure.core/defn get {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalField"]))} (^java.lang.Integer [^java.time.DayOfWeek this26344 ^java.time.temporal.TemporalField java-time-temporal-TemporalField26345] (.get this26344 java-time-temporal-TemporalField26345)))
(clojure.core/defn equals {:arglists (quote (["java.time.DayOfWeek" "java.lang.Object"]))} (^java.lang.Boolean [^java.time.DayOfWeek this26346 ^java.lang.Object java-lang-Object26347] (.equals this26346 java-lang-Object26347)))
