(ns cljc.java-time.day-of-week (:refer-clojure :exclude [get range format min max next name resolve short]) (:require [cljc.java-time.extn.calendar-awareness]) (:import [java.time DayOfWeek]))
(def saturday java.time.DayOfWeek/SATURDAY)
(def thursday java.time.DayOfWeek/THURSDAY)
(def friday java.time.DayOfWeek/FRIDAY)
(def wednesday java.time.DayOfWeek/WEDNESDAY)
(def sunday java.time.DayOfWeek/SUNDAY)
(def monday java.time.DayOfWeek/MONDAY)
(def tuesday java.time.DayOfWeek/TUESDAY)
(clojure.core/defn range {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalField"]))} (^java.time.temporal.ValueRange [^java.time.DayOfWeek this10926 ^java.time.temporal.TemporalField java-time-temporal-TemporalField10927] (.range this10926 java-time-temporal-TemporalField10927)))
(clojure.core/defn values {:arglists (quote ([]))} (^"java.lang.Class" [] (java.time.DayOfWeek/values)))
(clojure.core/defn value-of {:arglists (quote (["java.lang.String"] ["java.lang.Class" "java.lang.String"]))} (^java.time.DayOfWeek [^java.lang.String java-lang-String10928] (java.time.DayOfWeek/valueOf java-lang-String10928)) (^java.lang.Enum [^java.lang.Class java-lang-Class10929 ^java.lang.String java-lang-String10930] (java.time.DayOfWeek/valueOf java-lang-Class10929 java-lang-String10930)))
(clojure.core/defn of {:arglists (quote (["int"]))} (^java.time.DayOfWeek [^java.lang.Integer int10931] (java.time.DayOfWeek/of int10931)))
(clojure.core/defn ordinal {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.Integer [^java.time.DayOfWeek this10932] (.ordinal this10932)))
(clojure.core/defn plus {:arglists (quote (["java.time.DayOfWeek" "long"]))} (^java.time.DayOfWeek [^java.time.DayOfWeek this10933 ^long long10934] (.plus this10933 long10934)))
(clojure.core/defn query {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalQuery"]))} (^java.lang.Object [^java.time.DayOfWeek this10935 ^java.time.temporal.TemporalQuery java-time-temporal-TemporalQuery10936] (.query this10935 java-time-temporal-TemporalQuery10936)))
(clojure.core/defn to-string {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.String [^java.time.DayOfWeek this10937] (.toString this10937)))
(clojure.core/defn minus {:arglists (quote (["java.time.DayOfWeek" "long"]))} (^java.time.DayOfWeek [^java.time.DayOfWeek this10938 ^long long10939] (.minus this10938 long10939)))
(clojure.core/defn get-display-name {:arglists (quote (["java.time.DayOfWeek" "java.time.format.TextStyle" "java.util.Locale"]))} (^java.lang.String [^java.time.DayOfWeek this10940 ^java.time.format.TextStyle java-time-format-TextStyle10941 ^java.util.Locale java-util-Locale10942] (.getDisplayName this10940 java-time-format-TextStyle10941 java-util-Locale10942)))
(clojure.core/defn get-value {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.Integer [^java.time.DayOfWeek this10943] (.getValue this10943)))
(clojure.core/defn name {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.String [^java.time.DayOfWeek this10944] (.name this10944)))
(clojure.core/defn get-long {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalField"]))} (^long [^java.time.DayOfWeek this10945 ^java.time.temporal.TemporalField java-time-temporal-TemporalField10946] (.getLong this10945 java-time-temporal-TemporalField10946)))
(clojure.core/defn get-declaring-class {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.Class [^java.time.DayOfWeek this10947] (.getDeclaringClass this10947)))
(clojure.core/defn from {:arglists (quote (["java.time.temporal.TemporalAccessor"]))} (^java.time.DayOfWeek [^java.time.temporal.TemporalAccessor java-time-temporal-TemporalAccessor10948] (java.time.DayOfWeek/from java-time-temporal-TemporalAccessor10948)))
(clojure.core/defn is-supported {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalField"]))} (^java.lang.Boolean [^java.time.DayOfWeek this10949 ^java.time.temporal.TemporalField java-time-temporal-TemporalField10950] (.isSupported this10949 java-time-temporal-TemporalField10950)))
(clojure.core/defn hash-code {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.Integer [^java.time.DayOfWeek this10951] (.hashCode this10951)))
(clojure.core/defn adjust-into {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.Temporal"]))} (^java.time.temporal.Temporal [^java.time.DayOfWeek this10952 ^java.time.temporal.Temporal java-time-temporal-Temporal10953] (.adjustInto this10952 java-time-temporal-Temporal10953)))
(clojure.core/defn compare-to {:arglists (quote (["java.time.DayOfWeek" "java.lang.Object"] ["java.time.DayOfWeek" "java.lang.Enum"]))} (^java.lang.Integer [this10954 G__10955] (clojure.core/cond (clojure.core/and (clojure.core/instance? (java.lang.Class/forName "java.lang.Object") G__10955)) (clojure.core/let [G__10955 ^"java.lang.Object" G__10955] (.compareTo ^java.time.DayOfWeek this10954 G__10955)) (clojure.core/and (clojure.core/instance? (java.lang.Class/forName "java.lang.Enum") G__10955)) (clojure.core/let [G__10955 ^"java.lang.Enum" G__10955] (.compareTo ^java.time.DayOfWeek this10954 G__10955)) :else (throw (java.lang.IllegalArgumentException. "no corresponding java.time method with these args")))))
(clojure.core/defn get {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalField"]))} (^java.lang.Integer [^java.time.DayOfWeek this10956 ^java.time.temporal.TemporalField java-time-temporal-TemporalField10957] (.get this10956 java-time-temporal-TemporalField10957)))
(clojure.core/defn equals {:arglists (quote (["java.time.DayOfWeek" "java.lang.Object"]))} (^java.lang.Boolean [^java.time.DayOfWeek this10958 ^java.lang.Object java-lang-Object10959] (.equals this10958 java-lang-Object10959)))
