(ns cljc.java-time.duration (:refer-clojure :exclude [get range format min max next name resolve short]) (:require [cljc.java-time.extn.calendar-awareness]) (:import [java.time Duration]))
(def zero java.time.Duration/ZERO)
(clojure.core/defn minus-minutes {:arglists (quote (["java.time.Duration" "long"]))} (^java.time.Duration [^java.time.Duration this26746 ^long long26747] (.minusMinutes this26746 long26747)))
(clojure.core/defn to-nanos {:arglists (quote (["java.time.Duration"]))} (^long [^java.time.Duration this26748] (.toNanos this26748)))
(clojure.core/defn minus-millis {:arglists (quote (["java.time.Duration" "long"]))} (^java.time.Duration [^java.time.Duration this26749 ^long long26750] (.minusMillis this26749 long26750)))
(clojure.core/defn minus-hours {:arglists (quote (["java.time.Duration" "long"]))} (^java.time.Duration [^java.time.Duration this26751 ^long long26752] (.minusHours this26751 long26752)))
(clojure.core/defn of-days {:arglists (quote (["long"]))} (^java.time.Duration [^long long26753] (java.time.Duration/ofDays long26753)))
(clojure.core/defn is-negative {:arglists (quote (["java.time.Duration"]))} (^java.lang.Boolean [^java.time.Duration this26754] (.isNegative this26754)))
(clojure.core/defn of {:arglists (quote (["long" "java.time.temporal.TemporalUnit"]))} (^java.time.Duration [^long long26755 ^java.time.temporal.TemporalUnit java-time-temporal-TemporalUnit26756] (java.time.Duration/of long26755 java-time-temporal-TemporalUnit26756)))
(clojure.core/defn is-zero {:arglists (quote (["java.time.Duration"]))} (^java.lang.Boolean [^java.time.Duration this26757] (.isZero this26757)))
(clojure.core/defn multiplied-by {:arglists (quote (["java.time.Duration" "long"]))} (^java.time.Duration [^java.time.Duration this26758 ^long long26759] (.multipliedBy this26758 long26759)))
(clojure.core/defn with-nanos {:arglists (quote (["java.time.Duration" "int"]))} (^java.time.Duration [^java.time.Duration this26760 ^java.lang.Integer int26761] (.withNanos this26760 int26761)))
(clojure.core/defn get-units {:arglists (quote (["java.time.Duration"]))} (^java.util.List [^java.time.Duration this26762] (.getUnits this26762)))
(clojure.core/defn get-nano {:arglists (quote (["java.time.Duration"]))} (^java.lang.Integer [^java.time.Duration this26763] (.getNano this26763)))
(clojure.core/defn plus-millis {:arglists (quote (["java.time.Duration" "long"]))} (^java.time.Duration [^java.time.Duration this26764 ^long long26765] (.plusMillis this26764 long26765)))
(clojure.core/defn to-minutes {:arglists (quote (["java.time.Duration"]))} (^long [^java.time.Duration this26766] (.toMinutes this26766)))
(clojure.core/defn minus-seconds {:arglists (quote (["java.time.Duration" "long"]))} (^java.time.Duration [^java.time.Duration this26767 ^long long26768] (.minusSeconds this26767 long26768)))
(clojure.core/defn plus-nanos {:arglists (quote (["java.time.Duration" "long"]))} (^java.time.Duration [^java.time.Duration this26769 ^long long26770] (.plusNanos this26769 long26770)))
(clojure.core/defn plus {:arglists (quote (["java.time.Duration" "java.time.Duration"] ["java.time.Duration" "long" "java.time.temporal.TemporalUnit"]))} (^java.time.Duration [^java.time.Duration this26771 ^java.time.Duration java-time-Duration26772] (.plus this26771 java-time-Duration26772)) (^java.time.Duration [^java.time.Duration this26773 ^long long26774 ^java.time.temporal.TemporalUnit java-time-temporal-TemporalUnit26775] (.plus this26773 long26774 java-time-temporal-TemporalUnit26775)))
(clojure.core/defn divided-by {:arglists (quote (["java.time.Duration" "long"]))} (^java.time.Duration [^java.time.Duration this26776 ^long long26777] (.dividedBy this26776 long26777)))
(clojure.core/defn plus-minutes {:arglists (quote (["java.time.Duration" "long"]))} (^java.time.Duration [^java.time.Duration this26778 ^long long26779] (.plusMinutes this26778 long26779)))
(clojure.core/defn to-string {:arglists (quote (["java.time.Duration"]))} (^java.lang.String [^java.time.Duration this26780] (.toString this26780)))
(clojure.core/defn minus {:arglists (quote (["java.time.Duration" "long" "java.time.temporal.TemporalUnit"] ["java.time.Duration" "java.time.Duration"]))} (^java.time.Duration [^java.time.Duration this26781 ^long long26782 ^java.time.temporal.TemporalUnit java-time-temporal-TemporalUnit26783] (.minus this26781 long26782 java-time-temporal-TemporalUnit26783)) (^java.time.Duration [^java.time.Duration this26784 ^java.time.Duration java-time-Duration26785] (.minus this26784 java-time-Duration26785)))
(clojure.core/defn add-to {:arglists (quote (["java.time.Duration" "java.time.temporal.Temporal"]))} (^java.time.temporal.Temporal [^java.time.Duration this26786 ^java.time.temporal.Temporal java-time-temporal-Temporal26787] (.addTo this26786 java-time-temporal-Temporal26787)))
(clojure.core/defn plus-hours {:arglists (quote (["java.time.Duration" "long"]))} (^java.time.Duration [^java.time.Duration this26788 ^long long26789] (.plusHours this26788 long26789)))
(clojure.core/defn plus-days {:arglists (quote (["java.time.Duration" "long"]))} (^java.time.Duration [^java.time.Duration this26790 ^long long26791] (.plusDays this26790 long26791)))
(clojure.core/defn of-hours {:arglists (quote (["long"]))} (^java.time.Duration [^long long26792] (java.time.Duration/ofHours long26792)))
(clojure.core/defn to-millis {:arglists (quote (["java.time.Duration"]))} (^long [^java.time.Duration this26793] (.toMillis this26793)))
(clojure.core/defn to-hours {:arglists (quote (["java.time.Duration"]))} (^long [^java.time.Duration this26794] (.toHours this26794)))
(clojure.core/defn of-nanos {:arglists (quote (["long"]))} (^java.time.Duration [^long long26795] (java.time.Duration/ofNanos long26795)))
(clojure.core/defn of-millis {:arglists (quote (["long"]))} (^java.time.Duration [^long long26796] (java.time.Duration/ofMillis long26796)))
(clojure.core/defn negated {:arglists (quote (["java.time.Duration"]))} (^java.time.Duration [^java.time.Duration this26797] (.negated this26797)))
(clojure.core/defn abs {:arglists (quote (["java.time.Duration"]))} (^java.time.Duration [^java.time.Duration this26798] (.abs this26798)))
(clojure.core/defn between {:arglists (quote (["java.time.temporal.Temporal" "java.time.temporal.Temporal"]))} (^java.time.Duration [^java.time.temporal.Temporal java-time-temporal-Temporal26799 ^java.time.temporal.Temporal java-time-temporal-Temporal26800] (java.time.Duration/between java-time-temporal-Temporal26799 java-time-temporal-Temporal26800)))
(clojure.core/defn get-seconds {:arglists (quote (["java.time.Duration"]))} (^long [^java.time.Duration this26801] (.getSeconds this26801)))
(clojure.core/defn from {:arglists (quote (["java.time.temporal.TemporalAmount"]))} (^java.time.Duration [^java.time.temporal.TemporalAmount java-time-temporal-TemporalAmount26802] (java.time.Duration/from java-time-temporal-TemporalAmount26802)))
(clojure.core/defn minus-nanos {:arglists (quote (["java.time.Duration" "long"]))} (^java.time.Duration [^java.time.Duration this26803 ^long long26804] (.minusNanos this26803 long26804)))
(clojure.core/defn parse {:arglists (quote (["java.lang.CharSequence"]))} (^java.time.Duration [^java.lang.CharSequence java-lang-CharSequence26805] (java.time.Duration/parse java-lang-CharSequence26805)))
(clojure.core/defn hash-code {:arglists (quote (["java.time.Duration"]))} (^java.lang.Integer [^java.time.Duration this26806] (.hashCode this26806)))
(clojure.core/defn with-seconds {:arglists (quote (["java.time.Duration" "long"]))} (^java.time.Duration [^java.time.Duration this26807 ^long long26808] (.withSeconds this26807 long26808)))
(clojure.core/defn of-minutes {:arglists (quote (["long"]))} (^java.time.Duration [^long long26809] (java.time.Duration/ofMinutes long26809)))
(clojure.core/defn subtract-from {:arglists (quote (["java.time.Duration" "java.time.temporal.Temporal"]))} (^java.time.temporal.Temporal [^java.time.Duration this26810 ^java.time.temporal.Temporal java-time-temporal-Temporal26811] (.subtractFrom this26810 java-time-temporal-Temporal26811)))
(clojure.core/defn compare-to {:arglists (quote (["java.time.Duration" "java.time.Duration"]))} (^java.lang.Integer [^java.time.Duration this26812 ^java.time.Duration java-time-Duration26813] (.compareTo this26812 java-time-Duration26813)))
(clojure.core/defn plus-seconds {:arglists (quote (["java.time.Duration" "long"]))} (^java.time.Duration [^java.time.Duration this26814 ^long long26815] (.plusSeconds this26814 long26815)))
(clojure.core/defn get {:arglists (quote (["java.time.Duration" "java.time.temporal.TemporalUnit"]))} (^long [^java.time.Duration this26816 ^java.time.temporal.TemporalUnit java-time-temporal-TemporalUnit26817] (.get this26816 java-time-temporal-TemporalUnit26817)))
(clojure.core/defn equals {:arglists (quote (["java.time.Duration" "java.lang.Object"]))} (^java.lang.Boolean [^java.time.Duration this26818 ^java.lang.Object java-lang-Object26819] (.equals this26818 java-lang-Object26819)))
(clojure.core/defn of-seconds {:arglists (quote (["long" "long"] ["long"]))} (^java.time.Duration [^long long26820 ^long long26821] (java.time.Duration/ofSeconds long26820 long26821)) (^java.time.Duration [^long long26822] (java.time.Duration/ofSeconds long26822)))
(clojure.core/defn minus-days {:arglists (quote (["java.time.Duration" "long"]))} (^java.time.Duration [^java.time.Duration this26823 ^long long26824] (.minusDays this26823 long26824)))
(clojure.core/defn to-days {:arglists (quote (["java.time.Duration"]))} (^long [^java.time.Duration this26825] (.toDays this26825)))
