(ns cljc.java-time.month (:refer-clojure :exclude [get range format min max next name resolve short]) (:require [cljc.java-time.extn.calendar-awareness]) (:import [java.time Month]))
(def may java.time.Month/MAY)
(def december java.time.Month/DECEMBER)
(def june java.time.Month/JUNE)
(def september java.time.Month/SEPTEMBER)
(def february java.time.Month/FEBRUARY)
(def january java.time.Month/JANUARY)
(def november java.time.Month/NOVEMBER)
(def august java.time.Month/AUGUST)
(def july java.time.Month/JULY)
(def march java.time.Month/MARCH)
(def october java.time.Month/OCTOBER)
(def april java.time.Month/APRIL)
(clojure.core/defn range {:arglists (quote (["java.time.Month" "java.time.temporal.TemporalField"]))} (^java.time.temporal.ValueRange [^java.time.Month this11184 ^java.time.temporal.TemporalField java-time-temporal-TemporalField11185] (.range this11184 java-time-temporal-TemporalField11185)))
(clojure.core/defn values {:arglists (quote ([]))} (^"java.lang.Class" [] (java.time.Month/values)))
(clojure.core/defn value-of {:arglists (quote (["java.lang.String"] ["java.lang.Class" "java.lang.String"]))} (^java.time.Month [^java.lang.String java-lang-String11186] (java.time.Month/valueOf java-lang-String11186)) (^java.lang.Enum [^java.lang.Class java-lang-Class11187 ^java.lang.String java-lang-String11188] (java.time.Month/valueOf java-lang-Class11187 java-lang-String11188)))
(clojure.core/defn of {:arglists (quote (["int"]))} (^java.time.Month [^java.lang.Integer int11189] (java.time.Month/of int11189)))
(clojure.core/defn ordinal {:arglists (quote (["java.time.Month"]))} (^java.lang.Integer [^java.time.Month this11190] (.ordinal this11190)))
(clojure.core/defn first-month-of-quarter {:arglists (quote (["java.time.Month"]))} (^java.time.Month [^java.time.Month this11191] (.firstMonthOfQuarter this11191)))
(clojure.core/defn min-length {:arglists (quote (["java.time.Month"]))} (^java.lang.Integer [^java.time.Month this11192] (.minLength this11192)))
(clojure.core/defn plus {:arglists (quote (["java.time.Month" "long"]))} (^java.time.Month [^java.time.Month this11193 ^long long11194] (.plus this11193 long11194)))
(clojure.core/defn query {:arglists (quote (["java.time.Month" "java.time.temporal.TemporalQuery"]))} (^java.lang.Object [^java.time.Month this11195 ^java.time.temporal.TemporalQuery java-time-temporal-TemporalQuery11196] (.query this11195 java-time-temporal-TemporalQuery11196)))
(clojure.core/defn to-string {:arglists (quote (["java.time.Month"]))} (^java.lang.String [^java.time.Month this11197] (.toString this11197)))
(clojure.core/defn first-day-of-year {:arglists (quote (["java.time.Month" "boolean"]))} (^java.lang.Integer [^java.time.Month this11198 ^java.lang.Boolean boolean11199] (.firstDayOfYear this11198 boolean11199)))
(clojure.core/defn minus {:arglists (quote (["java.time.Month" "long"]))} (^java.time.Month [^java.time.Month this11200 ^long long11201] (.minus this11200 long11201)))
(clojure.core/defn get-display-name {:arglists (quote (["java.time.Month" "java.time.format.TextStyle" "java.util.Locale"]))} (^java.lang.String [^java.time.Month this11202 ^java.time.format.TextStyle java-time-format-TextStyle11203 ^java.util.Locale java-util-Locale11204] (.getDisplayName this11202 java-time-format-TextStyle11203 java-util-Locale11204)))
(clojure.core/defn get-value {:arglists (quote (["java.time.Month"]))} (^java.lang.Integer [^java.time.Month this11205] (.getValue this11205)))
(clojure.core/defn max-length {:arglists (quote (["java.time.Month"]))} (^java.lang.Integer [^java.time.Month this11206] (.maxLength this11206)))
(clojure.core/defn name {:arglists (quote (["java.time.Month"]))} (^java.lang.String [^java.time.Month this11207] (.name this11207)))
(clojure.core/defn get-long {:arglists (quote (["java.time.Month" "java.time.temporal.TemporalField"]))} (^long [^java.time.Month this11208 ^java.time.temporal.TemporalField java-time-temporal-TemporalField11209] (.getLong this11208 java-time-temporal-TemporalField11209)))
(clojure.core/defn length {:arglists (quote (["java.time.Month" "boolean"]))} (^java.lang.Integer [^java.time.Month this11210 ^java.lang.Boolean boolean11211] (.length this11210 boolean11211)))
(clojure.core/defn get-declaring-class {:arglists (quote (["java.time.Month"]))} (^java.lang.Class [^java.time.Month this11212] (.getDeclaringClass this11212)))
(clojure.core/defn from {:arglists (quote (["java.time.temporal.TemporalAccessor"]))} (^java.time.Month [^java.time.temporal.TemporalAccessor java-time-temporal-TemporalAccessor11213] (java.time.Month/from java-time-temporal-TemporalAccessor11213)))
(clojure.core/defn is-supported {:arglists (quote (["java.time.Month" "java.time.temporal.TemporalField"]))} (^java.lang.Boolean [^java.time.Month this11214 ^java.time.temporal.TemporalField java-time-temporal-TemporalField11215] (.isSupported this11214 java-time-temporal-TemporalField11215)))
(clojure.core/defn hash-code {:arglists (quote (["java.time.Month"]))} (^java.lang.Integer [^java.time.Month this11216] (.hashCode this11216)))
(clojure.core/defn adjust-into {:arglists (quote (["java.time.Month" "java.time.temporal.Temporal"]))} (^java.time.temporal.Temporal [^java.time.Month this11217 ^java.time.temporal.Temporal java-time-temporal-Temporal11218] (.adjustInto this11217 java-time-temporal-Temporal11218)))
(clojure.core/defn compare-to {:arglists (quote (["java.time.Month" "java.lang.Object"] ["java.time.Month" "java.lang.Enum"]))} (^java.lang.Integer [this11219 G__11220] (clojure.core/cond (clojure.core/and (clojure.core/instance? (java.lang.Class/forName "java.lang.Object") G__11220)) (clojure.core/let [G__11220 ^"java.lang.Object" G__11220] (.compareTo ^java.time.Month this11219 G__11220)) (clojure.core/and (clojure.core/instance? (java.lang.Class/forName "java.lang.Enum") G__11220)) (clojure.core/let [G__11220 ^"java.lang.Enum" G__11220] (.compareTo ^java.time.Month this11219 G__11220)) :else (throw (java.lang.IllegalArgumentException. "no corresponding java.time method with these args")))))
(clojure.core/defn get {:arglists (quote (["java.time.Month" "java.time.temporal.TemporalField"]))} (^java.lang.Integer [^java.time.Month this11221 ^java.time.temporal.TemporalField java-time-temporal-TemporalField11222] (.get this11221 java-time-temporal-TemporalField11222)))
(clojure.core/defn equals {:arglists (quote (["java.time.Month" "java.lang.Object"]))} (^java.lang.Boolean [^java.time.Month this11223 ^java.lang.Object java-lang-Object11224] (.equals this11223 java-lang-Object11224)))
