(ns cljc.java-time.period (:refer-clojure :exclude [get range format min max next name resolve short]) (:require [cljc.java-time.extn.calendar-awareness]) (:import [java.time Period]))
(def zero java.time.Period/ZERO)
(clojure.core/defn get-months {:arglists (quote (["java.time.Period"]))} (^java.lang.Integer [^java.time.Period this24742] (.getMonths this24742)))
(clojure.core/defn of-weeks {:arglists (quote (["int"]))} (^java.time.Period [^java.lang.Integer int24743] (java.time.Period/ofWeeks int24743)))
(clojure.core/defn of-days {:arglists (quote (["int"]))} (^java.time.Period [^java.lang.Integer int24744] (java.time.Period/ofDays int24744)))
(clojure.core/defn is-negative {:arglists (quote (["java.time.Period"]))} (^java.lang.Boolean [^java.time.Period this24745] (.isNegative this24745)))
(clojure.core/defn of {:arglists (quote (["int" "int" "int"]))} (^java.time.Period [^java.lang.Integer int24746 ^java.lang.Integer int24747 ^java.lang.Integer int24748] (java.time.Period/of int24746 int24747 int24748)))
(clojure.core/defn is-zero {:arglists (quote (["java.time.Period"]))} (^java.lang.Boolean [^java.time.Period this24749] (.isZero this24749)))
(clojure.core/defn multiplied-by {:arglists (quote (["java.time.Period" "int"]))} (^java.time.Period [^java.time.Period this24750 ^java.lang.Integer int24751] (.multipliedBy this24750 int24751)))
(clojure.core/defn get-units {:arglists (quote (["java.time.Period"]))} (^java.util.List [^java.time.Period this24752] (.getUnits this24752)))
(clojure.core/defn with-days {:arglists (quote (["java.time.Period" "int"]))} (^java.time.Period [^java.time.Period this24753 ^java.lang.Integer int24754] (.withDays this24753 int24754)))
(clojure.core/defn plus {:arglists (quote (["java.time.Period" "java.time.temporal.TemporalAmount"]))} (^java.time.Period [^java.time.Period this24755 ^java.time.temporal.TemporalAmount java-time-temporal-TemporalAmount24756] (.plus this24755 java-time-temporal-TemporalAmount24756)))
(clojure.core/defn of-months {:arglists (quote (["int"]))} (^java.time.Period [^java.lang.Integer int24757] (java.time.Period/ofMonths int24757)))
(clojure.core/defn to-string {:arglists (quote (["java.time.Period"]))} (^java.lang.String [^java.time.Period this24758] (.toString this24758)))
(clojure.core/defn plus-months {:arglists (quote (["java.time.Period" "long"]))} (^java.time.Period [^java.time.Period this24759 ^long long24760] (.plusMonths this24759 long24760)))
(clojure.core/defn minus-months {:arglists (quote (["java.time.Period" "long"]))} (^java.time.Period [^java.time.Period this24761 ^long long24762] (.minusMonths this24761 long24762)))
(clojure.core/defn minus {:arglists (quote (["java.time.Period" "java.time.temporal.TemporalAmount"]))} (^java.time.Period [^java.time.Period this24763 ^java.time.temporal.TemporalAmount java-time-temporal-TemporalAmount24764] (.minus this24763 java-time-temporal-TemporalAmount24764)))
(clojure.core/defn add-to {:arglists (quote (["java.time.Period" "java.time.temporal.Temporal"]))} (^java.time.temporal.Temporal [^java.time.Period this24765 ^java.time.temporal.Temporal java-time-temporal-Temporal24766] (.addTo this24765 java-time-temporal-Temporal24766)))
(clojure.core/defn to-total-months {:arglists (quote (["java.time.Period"]))} (^long [^java.time.Period this24767] (.toTotalMonths this24767)))
(clojure.core/defn plus-days {:arglists (quote (["java.time.Period" "long"]))} (^java.time.Period [^java.time.Period this24768 ^long long24769] (.plusDays this24768 long24769)))
(clojure.core/defn of-years {:arglists (quote (["int"]))} (^java.time.Period [^java.lang.Integer int24770] (java.time.Period/ofYears int24770)))
(clojure.core/defn get-days {:arglists (quote (["java.time.Period"]))} (^java.lang.Integer [^java.time.Period this24771] (.getDays this24771)))
(clojure.core/defn negated {:arglists (quote (["java.time.Period"]))} (^java.time.Period [^java.time.Period this24772] (.negated this24772)))
(clojure.core/defn get-years {:arglists (quote (["java.time.Period"]))} (^java.lang.Integer [^java.time.Period this24773] (.getYears this24773)))
(clojure.core/defn with-years {:arglists (quote (["java.time.Period" "int"]))} (^java.time.Period [^java.time.Period this24774 ^java.lang.Integer int24775] (.withYears this24774 int24775)))
(clojure.core/defn normalized {:arglists (quote (["java.time.Period"]))} (^java.time.Period [^java.time.Period this24776] (.normalized this24776)))
(clojure.core/defn with-months {:arglists (quote (["java.time.Period" "int"]))} (^java.time.Period [^java.time.Period this24777 ^java.lang.Integer int24778] (.withMonths this24777 int24778)))
(clojure.core/defn between {:arglists (quote (["java.time.LocalDate" "java.time.LocalDate"]))} (^java.time.Period [^java.time.LocalDate java-time-LocalDate24779 ^java.time.LocalDate java-time-LocalDate24780] (java.time.Period/between java-time-LocalDate24779 java-time-LocalDate24780)))
(clojure.core/defn from {:arglists (quote (["java.time.temporal.TemporalAmount"]))} (^java.time.Period [^java.time.temporal.TemporalAmount java-time-temporal-TemporalAmount24781] (java.time.Period/from java-time-temporal-TemporalAmount24781)))
(clojure.core/defn minus-years {:arglists (quote (["java.time.Period" "long"]))} (^java.time.Period [^java.time.Period this24782 ^long long24783] (.minusYears this24782 long24783)))
(clojure.core/defn get-chronology {:arglists (quote (["java.time.Period"]))} (^java.time.chrono.IsoChronology [^java.time.Period this24784] (.getChronology this24784)))
(clojure.core/defn parse {:arglists (quote (["java.lang.CharSequence"]))} (^java.time.Period [^java.lang.CharSequence java-lang-CharSequence24785] (java.time.Period/parse java-lang-CharSequence24785)))
(clojure.core/defn hash-code {:arglists (quote (["java.time.Period"]))} (^java.lang.Integer [^java.time.Period this24786] (.hashCode this24786)))
(clojure.core/defn subtract-from {:arglists (quote (["java.time.Period" "java.time.temporal.Temporal"]))} (^java.time.temporal.Temporal [^java.time.Period this24787 ^java.time.temporal.Temporal java-time-temporal-Temporal24788] (.subtractFrom this24787 java-time-temporal-Temporal24788)))
(clojure.core/defn get {:arglists (quote (["java.time.Period" "java.time.temporal.TemporalUnit"]))} (^long [^java.time.Period this24789 ^java.time.temporal.TemporalUnit java-time-temporal-TemporalUnit24790] (.get this24789 java-time-temporal-TemporalUnit24790)))
(clojure.core/defn equals {:arglists (quote (["java.time.Period" "java.lang.Object"]))} (^java.lang.Boolean [^java.time.Period this24791 ^java.lang.Object java-lang-Object24792] (.equals this24791 java-lang-Object24792)))
(clojure.core/defn plus-years {:arglists (quote (["java.time.Period" "long"]))} (^java.time.Period [^java.time.Period this24793 ^long long24794] (.plusYears this24793 long24794)))
(clojure.core/defn minus-days {:arglists (quote (["java.time.Period" "long"]))} (^java.time.Period [^java.time.Period this24795 ^long long24796] (.minusDays this24795 long24796)))
