(ns cljc.java-time.format.resolver-style (:refer-clojure :exclude [get range format min max next name resolve short]) (:require [cljc.java-time.extn.calendar-awareness] [java.time.format :refer [ResolverStyle]]))
(def smart (goog.object/get java.time.format.ResolverStyle "SMART"))
(def strict (goog.object/get java.time.format.ResolverStyle "STRICT"))
(def lenient (goog.object/get java.time.format.ResolverStyle "LENIENT"))
(clojure.core/defn values {:arglists (quote ([]))} (^"java.lang.Class" [] (js-invoke java.time.format.ResolverStyle "values")))
(clojure.core/defn value-of {:arglists (quote (["java.lang.String"] ["java.lang.Class" "java.lang.String"]))} (^js/JSJoda.ResolverStyle [^java.lang.String java-lang-String27914] (js-invoke java.time.format.ResolverStyle "valueOf" java-lang-String27914)) (^java.lang.Enum [^java.lang.Class java-lang-Class27915 ^java.lang.String java-lang-String27916] (js-invoke java.time.format.ResolverStyle "valueOf" java-lang-Class27915 java-lang-String27916)))
(clojure.core/defn ordinal {:arglists (quote (["java.time.format.ResolverStyle"]))} (^int [^js/JSJoda.ResolverStyle this27917] (.ordinal this27917)))
(clojure.core/defn to-string {:arglists (quote (["java.time.format.ResolverStyle"]))} (^java.lang.String [^js/JSJoda.ResolverStyle this27918] (.toString this27918)))
(clojure.core/defn name {:arglists (quote (["java.time.format.ResolverStyle"]))} (^java.lang.String [^js/JSJoda.ResolverStyle this27919] (.name this27919)))
(clojure.core/defn get-declaring-class {:arglists (quote (["java.time.format.ResolverStyle"]))} (^java.lang.Class [^js/JSJoda.ResolverStyle this27920] (.declaringClass this27920)))
(clojure.core/defn hash-code {:arglists (quote (["java.time.format.ResolverStyle"]))} (^int [^js/JSJoda.ResolverStyle this27921] (.hashCode this27921)))
(clojure.core/defn compare-to {:arglists (quote (["java.time.format.ResolverStyle" "java.lang.Enum"]))} (^int [^js/JSJoda.ResolverStyle this27922 ^java.lang.Enum java-lang-Enum27923] (.compareTo this27922 java-lang-Enum27923)))
(clojure.core/defn equals {:arglists (quote (["java.time.format.ResolverStyle" "java.lang.Object"]))} (^boolean [^js/JSJoda.ResolverStyle this27924 ^java.lang.Object java-lang-Object27925] (.equals this27924 java-lang-Object27925)))
