(ns cljc.java-time.format.sign-style (:refer-clojure :exclude [get range format min max next name resolve short]) (:require [cljc.java-time.extn.calendar-awareness] [java.time.format :refer [SignStyle]]))
(def exceeds-pad (goog.object/get java.time.format.SignStyle "EXCEEDS_PAD"))
(def normal (goog.object/get java.time.format.SignStyle "NORMAL"))
(def always (goog.object/get java.time.format.SignStyle "ALWAYS"))
(def never (goog.object/get java.time.format.SignStyle "NEVER"))
(def not-negative (goog.object/get java.time.format.SignStyle "NOT_NEGATIVE"))
(clojure.core/defn values {:arglists (quote ([]))} (^"java.lang.Class" [] (js-invoke java.time.format.SignStyle "values")))
(clojure.core/defn value-of {:arglists (quote (["java.lang.String"] ["java.lang.Class" "java.lang.String"]))} (^js/JSJoda.SignStyle [^java.lang.String java-lang-String12584] (js-invoke java.time.format.SignStyle "valueOf" java-lang-String12584)) (^java.lang.Enum [^java.lang.Class java-lang-Class12585 ^java.lang.String java-lang-String12586] (js-invoke java.time.format.SignStyle "valueOf" java-lang-Class12585 java-lang-String12586)))
(clojure.core/defn ordinal {:arglists (quote (["java.time.format.SignStyle"]))} (^int [^js/JSJoda.SignStyle this12587] (.ordinal this12587)))
(clojure.core/defn to-string {:arglists (quote (["java.time.format.SignStyle"]))} (^java.lang.String [^js/JSJoda.SignStyle this12588] (.toString this12588)))
(clojure.core/defn name {:arglists (quote (["java.time.format.SignStyle"]))} (^java.lang.String [^js/JSJoda.SignStyle this12589] (.name this12589)))
(clojure.core/defn get-declaring-class {:arglists (quote (["java.time.format.SignStyle"]))} (^java.lang.Class [^js/JSJoda.SignStyle this12590] (.declaringClass this12590)))
(clojure.core/defn hash-code {:arglists (quote (["java.time.format.SignStyle"]))} (^int [^js/JSJoda.SignStyle this12591] (.hashCode this12591)))
(clojure.core/defn compare-to {:arglists (quote (["java.time.format.SignStyle" "java.lang.Object"] ["java.time.format.SignStyle" "java.lang.Enum"]))} (^int [this12592 G__12593] (.compareTo ^js/JSJoda.SignStyle this12592 G__12593)))
(clojure.core/defn equals {:arglists (quote (["java.time.format.SignStyle" "java.lang.Object"]))} (^boolean [^js/JSJoda.SignStyle this12594 ^java.lang.Object java-lang-Object12595] (.equals this12594 java-lang-Object12595)))
