(ns cljc.java-time.temporal.chrono-field (:refer-clojure :exclude [get range format min max next name resolve short]) (:require [cljc.java-time.extn.calendar-awareness] [java.time.temporal :refer [ChronoField]]))
(def milli-of-second (goog.object/get java.time.temporal.ChronoField "MILLI_OF_SECOND"))
(def year-of-era (goog.object/get java.time.temporal.ChronoField "YEAR_OF_ERA"))
(def clock-hour-of-day (goog.object/get java.time.temporal.ChronoField "CLOCK_HOUR_OF_DAY"))
(def era (goog.object/get java.time.temporal.ChronoField "ERA"))
(def instant-seconds (goog.object/get java.time.temporal.ChronoField "INSTANT_SECONDS"))
(def ampm-of-day (goog.object/get java.time.temporal.ChronoField "AMPM_OF_DAY"))
(def offset-seconds (goog.object/get java.time.temporal.ChronoField "OFFSET_SECONDS"))
(def nano-of-second (goog.object/get java.time.temporal.ChronoField "NANO_OF_SECOND"))
(def nano-of-day (goog.object/get java.time.temporal.ChronoField "NANO_OF_DAY"))
(def aligned-day-of-week-in-month (goog.object/get java.time.temporal.ChronoField "ALIGNED_DAY_OF_WEEK_IN_MONTH"))
(def month-of-year (goog.object/get java.time.temporal.ChronoField "MONTH_OF_YEAR"))
(def hour-of-ampm (goog.object/get java.time.temporal.ChronoField "HOUR_OF_AMPM"))
(def year (goog.object/get java.time.temporal.ChronoField "YEAR"))
(def micro-of-second (goog.object/get java.time.temporal.ChronoField "MICRO_OF_SECOND"))
(def aligned-week-of-year (goog.object/get java.time.temporal.ChronoField "ALIGNED_WEEK_OF_YEAR"))
(def proleptic-month (goog.object/get java.time.temporal.ChronoField "PROLEPTIC_MONTH"))
(def day-of-month (goog.object/get java.time.temporal.ChronoField "DAY_OF_MONTH"))
(def second-of-minute (goog.object/get java.time.temporal.ChronoField "SECOND_OF_MINUTE"))
(def second-of-day (goog.object/get java.time.temporal.ChronoField "SECOND_OF_DAY"))
(def epoch-day (goog.object/get java.time.temporal.ChronoField "EPOCH_DAY"))
(def day-of-year (goog.object/get java.time.temporal.ChronoField "DAY_OF_YEAR"))
(def aligned-week-of-month (goog.object/get java.time.temporal.ChronoField "ALIGNED_WEEK_OF_MONTH"))
(def day-of-week (goog.object/get java.time.temporal.ChronoField "DAY_OF_WEEK"))
(def clock-hour-of-ampm (goog.object/get java.time.temporal.ChronoField "CLOCK_HOUR_OF_AMPM"))
(def minute-of-day (goog.object/get java.time.temporal.ChronoField "MINUTE_OF_DAY"))
(def aligned-day-of-week-in-year (goog.object/get java.time.temporal.ChronoField "ALIGNED_DAY_OF_WEEK_IN_YEAR"))
(def minute-of-hour (goog.object/get java.time.temporal.ChronoField "MINUTE_OF_HOUR"))
(def hour-of-day (goog.object/get java.time.temporal.ChronoField "HOUR_OF_DAY"))
(def milli-of-day (goog.object/get java.time.temporal.ChronoField "MILLI_OF_DAY"))
(def micro-of-day (goog.object/get java.time.temporal.ChronoField "MICRO_OF_DAY"))
(clojure.core/defn get-range-unit {:arglists (quote (["java.time.temporal.ChronoField"]))} (^js/JSJoda.TemporalUnit [^js/JSJoda.ChronoField this12078] (.rangeUnit this12078)))
(clojure.core/defn range {:arglists (quote (["java.time.temporal.ChronoField"]))} (^js/JSJoda.ValueRange [^js/JSJoda.ChronoField this12079] (.range this12079)))
(clojure.core/defn values {:arglists (quote ([]))} (^"java.lang.Class" [] (js-invoke java.time.temporal.ChronoField "values")))
(clojure.core/defn value-of {:arglists (quote (["java.lang.String"] ["java.lang.Class" "java.lang.String"]))} (^js/JSJoda.ChronoField [^java.lang.String java-lang-String12080] (js-invoke java.time.temporal.ChronoField "valueOf" java-lang-String12080)) (^java.lang.Enum [^java.lang.Class java-lang-Class12081 ^java.lang.String java-lang-String12082] (js-invoke java.time.temporal.ChronoField "valueOf" java-lang-Class12081 java-lang-String12082)))
(clojure.core/defn resolve {:arglists (quote (["java.time.temporal.ChronoField" "java.util.Map" "java.time.temporal.TemporalAccessor" "java.time.format.ResolverStyle"]))} (^js/JSJoda.TemporalAccessor [^js/JSJoda.ChronoField this12083 ^java.util.Map java-util-Map12084 ^js/JSJoda.TemporalAccessor java-time-temporal-TemporalAccessor12085 ^js/JSJoda.ResolverStyle java-time-format-ResolverStyle12086] (.resolve this12083 java-util-Map12084 java-time-temporal-TemporalAccessor12085 java-time-format-ResolverStyle12086)))
(clojure.core/defn ordinal {:arglists (quote (["java.time.temporal.ChronoField"]))} (^int [^js/JSJoda.ChronoField this12087] (.ordinal this12087)))
(clojure.core/defn check-valid-int-value {:arglists (quote (["java.time.temporal.ChronoField" "long"]))} (^int [^js/JSJoda.ChronoField this12088 ^long long12089] (.checkValidIntValue this12088 long12089)))
(clojure.core/defn get-base-unit {:arglists (quote (["java.time.temporal.ChronoField"]))} (^js/JSJoda.TemporalUnit [^js/JSJoda.ChronoField this12090] (.baseUnit this12090)))
(clojure.core/defn to-string {:arglists (quote (["java.time.temporal.ChronoField"]))} (^java.lang.String [^js/JSJoda.ChronoField this12091] (.toString this12091)))
(clojure.core/defn is-date-based {:arglists (quote (["java.time.temporal.ChronoField"]))} (^boolean [^js/JSJoda.ChronoField this12092] (.isDateBased this12092)))
(clojure.core/defn get-display-name {:arglists (quote (["java.time.temporal.ChronoField" "java.util.Locale"]))} (^java.lang.String [^js/JSJoda.ChronoField this12093 ^java.util.Locale java-util-Locale12094] (.displayName this12093 java-util-Locale12094)))
(clojure.core/defn name {:arglists (quote (["java.time.temporal.ChronoField"]))} (^java.lang.String [^js/JSJoda.ChronoField this12095] (.name this12095)))
(clojure.core/defn is-supported-by {:arglists (quote (["java.time.temporal.ChronoField" "java.time.temporal.TemporalAccessor"]))} (^boolean [^js/JSJoda.ChronoField this12096 ^js/JSJoda.TemporalAccessor java-time-temporal-TemporalAccessor12097] (.isSupportedBy this12096 java-time-temporal-TemporalAccessor12097)))
(clojure.core/defn range-refined-by {:arglists (quote (["java.time.temporal.ChronoField" "java.time.temporal.TemporalAccessor"]))} (^js/JSJoda.ValueRange [^js/JSJoda.ChronoField this12098 ^js/JSJoda.TemporalAccessor java-time-temporal-TemporalAccessor12099] (.rangeRefinedBy this12098 java-time-temporal-TemporalAccessor12099)))
(clojure.core/defn get-declaring-class {:arglists (quote (["java.time.temporal.ChronoField"]))} (^java.lang.Class [^js/JSJoda.ChronoField this12100] (.declaringClass this12100)))
(clojure.core/defn hash-code {:arglists (quote (["java.time.temporal.ChronoField"]))} (^int [^js/JSJoda.ChronoField this12101] (.hashCode this12101)))
(clojure.core/defn adjust-into {:arglists (quote (["java.time.temporal.ChronoField" "java.time.temporal.Temporal" "long"]))} (^js/JSJoda.Temporal [^js/JSJoda.ChronoField this12102 ^js/JSJoda.Temporal java-time-temporal-Temporal12103 ^long long12104] (.adjustInto this12102 java-time-temporal-Temporal12103 long12104)))
(clojure.core/defn get-from {:arglists (quote (["java.time.temporal.ChronoField" "java.time.temporal.TemporalAccessor"]))} (^long [^js/JSJoda.ChronoField this12105 ^js/JSJoda.TemporalAccessor java-time-temporal-TemporalAccessor12106] (.from this12105 java-time-temporal-TemporalAccessor12106)))
(clojure.core/defn compare-to {:arglists (quote (["java.time.temporal.ChronoField" "java.lang.Object"] ["java.time.temporal.ChronoField" "java.lang.Enum"]))} (^int [this12107 G__12108] (.compareTo ^js/JSJoda.ChronoField this12107 G__12108)))
(clojure.core/defn equals {:arglists (quote (["java.time.temporal.ChronoField" "java.lang.Object"]))} (^boolean [^js/JSJoda.ChronoField this12109 ^java.lang.Object java-lang-Object12110] (.equals this12109 java-lang-Object12110)))
(clojure.core/defn is-time-based {:arglists (quote (["java.time.temporal.ChronoField"]))} (^boolean [^js/JSJoda.ChronoField this12111] (.isTimeBased this12111)))
(clojure.core/defn check-valid-value {:arglists (quote (["java.time.temporal.ChronoField" "long"]))} (^long [^js/JSJoda.ChronoField this12112 ^long long12113] (.checkValidValue this12112 long12113)))
