(ns cljc.java-time.day-of-week (:refer-clojure :exclude [get range format min max next name resolve short]) (:require [cljc.java-time.extn.calendar-awareness] [java.time :refer [DayOfWeek]]))
(def saturday (goog.object/get java.time.DayOfWeek "SATURDAY"))
(def thursday (goog.object/get java.time.DayOfWeek "THURSDAY"))
(def friday (goog.object/get java.time.DayOfWeek "FRIDAY"))
(def wednesday (goog.object/get java.time.DayOfWeek "WEDNESDAY"))
(def sunday (goog.object/get java.time.DayOfWeek "SUNDAY"))
(def monday (goog.object/get java.time.DayOfWeek "MONDAY"))
(def tuesday (goog.object/get java.time.DayOfWeek "TUESDAY"))
(clojure.core/defn range {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalField"]))} (^js/JSJoda.ValueRange [^js/JSJoda.DayOfWeek this26348 ^js/JSJoda.TemporalField java-time-temporal-TemporalField26349] (.range this26348 java-time-temporal-TemporalField26349)))
(clojure.core/defn values {:arglists (quote ([]))} (^"java.lang.Class" [] (js-invoke java.time.DayOfWeek "values")))
(clojure.core/defn value-of {:arglists (quote (["java.lang.String"] ["java.lang.Class" "java.lang.String"]))} (^js/JSJoda.DayOfWeek [^java.lang.String java-lang-String26350] (js-invoke java.time.DayOfWeek "valueOf" java-lang-String26350)) (^java.lang.Enum [^java.lang.Class java-lang-Class26351 ^java.lang.String java-lang-String26352] (js-invoke java.time.DayOfWeek "valueOf" java-lang-Class26351 java-lang-String26352)))
(clojure.core/defn of {:arglists (quote (["int"]))} (^js/JSJoda.DayOfWeek [^int int26353] (js-invoke java.time.DayOfWeek "of" int26353)))
(clojure.core/defn ordinal {:arglists (quote (["java.time.DayOfWeek"]))} (^int [^js/JSJoda.DayOfWeek this26354] (.ordinal this26354)))
(clojure.core/defn plus {:arglists (quote (["java.time.DayOfWeek" "long"]))} (^js/JSJoda.DayOfWeek [^js/JSJoda.DayOfWeek this26355 ^long long26356] (.plus this26355 long26356)))
(clojure.core/defn query {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalQuery"]))} (^java.lang.Object [^js/JSJoda.DayOfWeek this26357 ^js/JSJoda.TemporalQuery java-time-temporal-TemporalQuery26358] (.query this26357 java-time-temporal-TemporalQuery26358)))
(clojure.core/defn to-string {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.String [^js/JSJoda.DayOfWeek this26359] (.toString this26359)))
(clojure.core/defn minus {:arglists (quote (["java.time.DayOfWeek" "long"]))} (^js/JSJoda.DayOfWeek [^js/JSJoda.DayOfWeek this26360 ^long long26361] (.minus this26360 long26361)))
(clojure.core/defn get-display-name {:arglists (quote (["java.time.DayOfWeek" "java.time.format.TextStyle" "java.util.Locale"]))} (^java.lang.String [^js/JSJoda.DayOfWeek this26362 ^js/JSJoda.TextStyle java-time-format-TextStyle26363 ^java.util.Locale java-util-Locale26364] (.displayName this26362 java-time-format-TextStyle26363 java-util-Locale26364)))
(clojure.core/defn get-value {:arglists (quote (["java.time.DayOfWeek"]))} (^int [^js/JSJoda.DayOfWeek this26365] (.value this26365)))
(clojure.core/defn name {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.String [^js/JSJoda.DayOfWeek this26366] (.name this26366)))
(clojure.core/defn get-long {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalField"]))} (^long [^js/JSJoda.DayOfWeek this26367 ^js/JSJoda.TemporalField java-time-temporal-TemporalField26368] (.getLong this26367 java-time-temporal-TemporalField26368)))
(clojure.core/defn get-declaring-class {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.Class [^js/JSJoda.DayOfWeek this26369] (.declaringClass this26369)))
(clojure.core/defn from {:arglists (quote (["java.time.temporal.TemporalAccessor"]))} (^js/JSJoda.DayOfWeek [^js/JSJoda.TemporalAccessor java-time-temporal-TemporalAccessor26370] (js-invoke java.time.DayOfWeek "from" java-time-temporal-TemporalAccessor26370)))
(clojure.core/defn is-supported {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalField"]))} (^boolean [^js/JSJoda.DayOfWeek this26371 ^js/JSJoda.TemporalField java-time-temporal-TemporalField26372] (.isSupported this26371 java-time-temporal-TemporalField26372)))
(clojure.core/defn hash-code {:arglists (quote (["java.time.DayOfWeek"]))} (^int [^js/JSJoda.DayOfWeek this26373] (.hashCode this26373)))
(clojure.core/defn adjust-into {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.Temporal"]))} (^js/JSJoda.Temporal [^js/JSJoda.DayOfWeek this26374 ^js/JSJoda.Temporal java-time-temporal-Temporal26375] (.adjustInto this26374 java-time-temporal-Temporal26375)))
(clojure.core/defn compare-to {:arglists (quote (["java.time.DayOfWeek" "java.lang.Enum"]))} (^int [^js/JSJoda.DayOfWeek this26376 ^java.lang.Enum java-lang-Enum26377] (.compareTo this26376 java-lang-Enum26377)))
(clojure.core/defn get {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalField"]))} (^int [^js/JSJoda.DayOfWeek this26378 ^js/JSJoda.TemporalField java-time-temporal-TemporalField26379] (.get this26378 java-time-temporal-TemporalField26379)))
(clojure.core/defn equals {:arglists (quote (["java.time.DayOfWeek" "java.lang.Object"]))} (^boolean [^js/JSJoda.DayOfWeek this26380 ^java.lang.Object java-lang-Object26381] (.equals this26380 java-lang-Object26381)))
