(ns cljc.java-time.day-of-week (:refer-clojure :exclude [get range format min max next name resolve short]) (:require [cljc.java-time.extn.calendar-awareness] [java.time :refer [DayOfWeek]]))
(def saturday (goog.object/get java.time.DayOfWeek "SATURDAY"))
(def thursday (goog.object/get java.time.DayOfWeek "THURSDAY"))
(def friday (goog.object/get java.time.DayOfWeek "FRIDAY"))
(def wednesday (goog.object/get java.time.DayOfWeek "WEDNESDAY"))
(def sunday (goog.object/get java.time.DayOfWeek "SUNDAY"))
(def monday (goog.object/get java.time.DayOfWeek "MONDAY"))
(def tuesday (goog.object/get java.time.DayOfWeek "TUESDAY"))
(clojure.core/defn range {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalField"]))} (^js/JSJoda.ValueRange [^js/JSJoda.DayOfWeek this10960 ^js/JSJoda.TemporalField java-time-temporal-TemporalField10961] (.range this10960 java-time-temporal-TemporalField10961)))
(clojure.core/defn values {:arglists (quote ([]))} (^"java.lang.Class" [] (js-invoke java.time.DayOfWeek "values")))
(clojure.core/defn value-of {:arglists (quote (["java.lang.String"] ["java.lang.Class" "java.lang.String"]))} (^js/JSJoda.DayOfWeek [^java.lang.String java-lang-String10962] (js-invoke java.time.DayOfWeek "valueOf" java-lang-String10962)) (^java.lang.Enum [^java.lang.Class java-lang-Class10963 ^java.lang.String java-lang-String10964] (js-invoke java.time.DayOfWeek "valueOf" java-lang-Class10963 java-lang-String10964)))
(clojure.core/defn of {:arglists (quote (["int"]))} (^js/JSJoda.DayOfWeek [^int int10965] (js-invoke java.time.DayOfWeek "of" int10965)))
(clojure.core/defn ordinal {:arglists (quote (["java.time.DayOfWeek"]))} (^int [^js/JSJoda.DayOfWeek this10966] (.ordinal this10966)))
(clojure.core/defn plus {:arglists (quote (["java.time.DayOfWeek" "long"]))} (^js/JSJoda.DayOfWeek [^js/JSJoda.DayOfWeek this10967 ^long long10968] (.plus this10967 long10968)))
(clojure.core/defn query {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalQuery"]))} (^java.lang.Object [^js/JSJoda.DayOfWeek this10969 ^js/JSJoda.TemporalQuery java-time-temporal-TemporalQuery10970] (.query this10969 java-time-temporal-TemporalQuery10970)))
(clojure.core/defn to-string {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.String [^js/JSJoda.DayOfWeek this10971] (.toString this10971)))
(clojure.core/defn minus {:arglists (quote (["java.time.DayOfWeek" "long"]))} (^js/JSJoda.DayOfWeek [^js/JSJoda.DayOfWeek this10972 ^long long10973] (.minus this10972 long10973)))
(clojure.core/defn get-display-name {:arglists (quote (["java.time.DayOfWeek" "java.time.format.TextStyle" "java.util.Locale"]))} (^java.lang.String [^js/JSJoda.DayOfWeek this10974 ^js/JSJoda.TextStyle java-time-format-TextStyle10975 ^java.util.Locale java-util-Locale10976] (.displayName this10974 java-time-format-TextStyle10975 java-util-Locale10976)))
(clojure.core/defn get-value {:arglists (quote (["java.time.DayOfWeek"]))} (^int [^js/JSJoda.DayOfWeek this10977] (.value this10977)))
(clojure.core/defn name {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.String [^js/JSJoda.DayOfWeek this10978] (.name this10978)))
(clojure.core/defn get-long {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalField"]))} (^long [^js/JSJoda.DayOfWeek this10979 ^js/JSJoda.TemporalField java-time-temporal-TemporalField10980] (.getLong this10979 java-time-temporal-TemporalField10980)))
(clojure.core/defn get-declaring-class {:arglists (quote (["java.time.DayOfWeek"]))} (^java.lang.Class [^js/JSJoda.DayOfWeek this10981] (.declaringClass this10981)))
(clojure.core/defn from {:arglists (quote (["java.time.temporal.TemporalAccessor"]))} (^js/JSJoda.DayOfWeek [^js/JSJoda.TemporalAccessor java-time-temporal-TemporalAccessor10982] (js-invoke java.time.DayOfWeek "from" java-time-temporal-TemporalAccessor10982)))
(clojure.core/defn is-supported {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalField"]))} (^boolean [^js/JSJoda.DayOfWeek this10983 ^js/JSJoda.TemporalField java-time-temporal-TemporalField10984] (.isSupported this10983 java-time-temporal-TemporalField10984)))
(clojure.core/defn hash-code {:arglists (quote (["java.time.DayOfWeek"]))} (^int [^js/JSJoda.DayOfWeek this10985] (.hashCode this10985)))
(clojure.core/defn adjust-into {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.Temporal"]))} (^js/JSJoda.Temporal [^js/JSJoda.DayOfWeek this10986 ^js/JSJoda.Temporal java-time-temporal-Temporal10987] (.adjustInto this10986 java-time-temporal-Temporal10987)))
(clojure.core/defn compare-to {:arglists (quote (["java.time.DayOfWeek" "java.lang.Object"] ["java.time.DayOfWeek" "java.lang.Enum"]))} (^int [this10988 G__10989] (.compareTo ^js/JSJoda.DayOfWeek this10988 G__10989)))
(clojure.core/defn get {:arglists (quote (["java.time.DayOfWeek" "java.time.temporal.TemporalField"]))} (^int [^js/JSJoda.DayOfWeek this10990 ^js/JSJoda.TemporalField java-time-temporal-TemporalField10991] (.get this10990 java-time-temporal-TemporalField10991)))
(clojure.core/defn equals {:arglists (quote (["java.time.DayOfWeek" "java.lang.Object"]))} (^boolean [^js/JSJoda.DayOfWeek this10992 ^java.lang.Object java-lang-Object10993] (.equals this10992 java-lang-Object10993)))
