(ns cljc.java-time.duration (:refer-clojure :exclude [get range format min max next name resolve short]) (:require [cljc.java-time.extn.calendar-awareness] [java.time :refer [Duration]]))
(def zero (goog.object/get java.time.Duration "ZERO"))
(clojure.core/defn minus-minutes {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26826 ^long long26827] (.minusMinutes this26826 long26827)))
(clojure.core/defn to-nanos {:arglists (quote (["java.time.Duration"]))} (^long [^js/JSJoda.Duration this26828] (.toNanos this26828)))
(clojure.core/defn minus-millis {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26829 ^long long26830] (.minusMillis this26829 long26830)))
(clojure.core/defn minus-hours {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26831 ^long long26832] (.minusHours this26831 long26832)))
(clojure.core/defn of-days {:arglists (quote (["long"]))} (^js/JSJoda.Duration [^long long26833] (js-invoke java.time.Duration "ofDays" long26833)))
(clojure.core/defn is-negative {:arglists (quote (["java.time.Duration"]))} (^boolean [^js/JSJoda.Duration this26834] (.isNegative this26834)))
(clojure.core/defn of {:arglists (quote (["long" "java.time.temporal.TemporalUnit"]))} (^js/JSJoda.Duration [^long long26835 ^js/JSJoda.TemporalUnit java-time-temporal-TemporalUnit26836] (js-invoke java.time.Duration "of" long26835 java-time-temporal-TemporalUnit26836)))
(clojure.core/defn is-zero {:arglists (quote (["java.time.Duration"]))} (^boolean [^js/JSJoda.Duration this26837] (.isZero this26837)))
(clojure.core/defn multiplied-by {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26838 ^long long26839] (.multipliedBy this26838 long26839)))
(clojure.core/defn with-nanos {:arglists (quote (["java.time.Duration" "int"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26840 ^int int26841] (.withNanos this26840 int26841)))
(clojure.core/defn get-units {:arglists (quote (["java.time.Duration"]))} (^java.util.List [^js/JSJoda.Duration this26842] (.units this26842)))
(clojure.core/defn get-nano {:arglists (quote (["java.time.Duration"]))} (^int [^js/JSJoda.Duration this26843] (.nano this26843)))
(clojure.core/defn plus-millis {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26844 ^long long26845] (.plusMillis this26844 long26845)))
(clojure.core/defn to-minutes {:arglists (quote (["java.time.Duration"]))} (^long [^js/JSJoda.Duration this26846] (.toMinutes this26846)))
(clojure.core/defn minus-seconds {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26847 ^long long26848] (.minusSeconds this26847 long26848)))
(clojure.core/defn plus-nanos {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26849 ^long long26850] (.plusNanos this26849 long26850)))
(clojure.core/defn plus {:arglists (quote (["java.time.Duration" "java.time.Duration"] ["java.time.Duration" "long" "java.time.temporal.TemporalUnit"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26851 ^js/JSJoda.Duration java-time-Duration26852] (.plus this26851 java-time-Duration26852)) (^js/JSJoda.Duration [^js/JSJoda.Duration this26853 ^long long26854 ^js/JSJoda.TemporalUnit java-time-temporal-TemporalUnit26855] (.plus this26853 long26854 java-time-temporal-TemporalUnit26855)))
(clojure.core/defn divided-by {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26856 ^long long26857] (.dividedBy this26856 long26857)))
(clojure.core/defn plus-minutes {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26858 ^long long26859] (.plusMinutes this26858 long26859)))
(clojure.core/defn to-string {:arglists (quote (["java.time.Duration"]))} (^java.lang.String [^js/JSJoda.Duration this26860] (.toString this26860)))
(clojure.core/defn minus {:arglists (quote (["java.time.Duration" "long" "java.time.temporal.TemporalUnit"] ["java.time.Duration" "java.time.Duration"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26861 ^long long26862 ^js/JSJoda.TemporalUnit java-time-temporal-TemporalUnit26863] (.minus this26861 long26862 java-time-temporal-TemporalUnit26863)) (^js/JSJoda.Duration [^js/JSJoda.Duration this26864 ^js/JSJoda.Duration java-time-Duration26865] (.minus this26864 java-time-Duration26865)))
(clojure.core/defn add-to {:arglists (quote (["java.time.Duration" "java.time.temporal.Temporal"]))} (^js/JSJoda.Temporal [^js/JSJoda.Duration this26866 ^js/JSJoda.Temporal java-time-temporal-Temporal26867] (.addTo this26866 java-time-temporal-Temporal26867)))
(clojure.core/defn plus-hours {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26868 ^long long26869] (.plusHours this26868 long26869)))
(clojure.core/defn plus-days {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26870 ^long long26871] (.plusDays this26870 long26871)))
(clojure.core/defn of-hours {:arglists (quote (["long"]))} (^js/JSJoda.Duration [^long long26872] (js-invoke java.time.Duration "ofHours" long26872)))
(clojure.core/defn to-millis {:arglists (quote (["java.time.Duration"]))} (^long [^js/JSJoda.Duration this26873] (.toMillis this26873)))
(clojure.core/defn to-hours {:arglists (quote (["java.time.Duration"]))} (^long [^js/JSJoda.Duration this26874] (.toHours this26874)))
(clojure.core/defn of-nanos {:arglists (quote (["long"]))} (^js/JSJoda.Duration [^long long26875] (js-invoke java.time.Duration "ofNanos" long26875)))
(clojure.core/defn of-millis {:arglists (quote (["long"]))} (^js/JSJoda.Duration [^long long26876] (js-invoke java.time.Duration "ofMillis" long26876)))
(clojure.core/defn negated {:arglists (quote (["java.time.Duration"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26877] (.negated this26877)))
(clojure.core/defn abs {:arglists (quote (["java.time.Duration"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26878] (.abs this26878)))
(clojure.core/defn between {:arglists (quote (["java.time.temporal.Temporal" "java.time.temporal.Temporal"]))} (^js/JSJoda.Duration [^js/JSJoda.Temporal java-time-temporal-Temporal26879 ^js/JSJoda.Temporal java-time-temporal-Temporal26880] (js-invoke java.time.Duration "between" java-time-temporal-Temporal26879 java-time-temporal-Temporal26880)))
(clojure.core/defn get-seconds {:arglists (quote (["java.time.Duration"]))} (^long [^js/JSJoda.Duration this26881] (.seconds this26881)))
(clojure.core/defn from {:arglists (quote (["java.time.temporal.TemporalAmount"]))} (^js/JSJoda.Duration [^js/JSJoda.TemporalAmount java-time-temporal-TemporalAmount26882] (js-invoke java.time.Duration "from" java-time-temporal-TemporalAmount26882)))
(clojure.core/defn minus-nanos {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26883 ^long long26884] (.minusNanos this26883 long26884)))
(clojure.core/defn parse {:arglists (quote (["java.lang.CharSequence"]))} (^js/JSJoda.Duration [^java.lang.CharSequence java-lang-CharSequence26885] (js-invoke java.time.Duration "parse" java-lang-CharSequence26885)))
(clojure.core/defn hash-code {:arglists (quote (["java.time.Duration"]))} (^int [^js/JSJoda.Duration this26886] (.hashCode this26886)))
(clojure.core/defn with-seconds {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26887 ^long long26888] (.withSeconds this26887 long26888)))
(clojure.core/defn of-minutes {:arglists (quote (["long"]))} (^js/JSJoda.Duration [^long long26889] (js-invoke java.time.Duration "ofMinutes" long26889)))
(clojure.core/defn subtract-from {:arglists (quote (["java.time.Duration" "java.time.temporal.Temporal"]))} (^js/JSJoda.Temporal [^js/JSJoda.Duration this26890 ^js/JSJoda.Temporal java-time-temporal-Temporal26891] (.subtractFrom this26890 java-time-temporal-Temporal26891)))
(clojure.core/defn compare-to {:arglists (quote (["java.time.Duration" "java.time.Duration"]))} (^int [^js/JSJoda.Duration this26892 ^js/JSJoda.Duration java-time-Duration26893] (.compareTo this26892 java-time-Duration26893)))
(clojure.core/defn plus-seconds {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26894 ^long long26895] (.plusSeconds this26894 long26895)))
(clojure.core/defn get {:arglists (quote (["java.time.Duration" "java.time.temporal.TemporalUnit"]))} (^long [^js/JSJoda.Duration this26896 ^js/JSJoda.TemporalUnit java-time-temporal-TemporalUnit26897] (.get this26896 java-time-temporal-TemporalUnit26897)))
(clojure.core/defn equals {:arglists (quote (["java.time.Duration" "java.lang.Object"]))} (^boolean [^js/JSJoda.Duration this26898 ^java.lang.Object java-lang-Object26899] (.equals this26898 java-lang-Object26899)))
(clojure.core/defn of-seconds {:arglists (quote (["long" "long"] ["long"]))} (^js/JSJoda.Duration [^long long26900 ^long long26901] (js-invoke java.time.Duration "ofSeconds" long26900 long26901)) (^js/JSJoda.Duration [^long long26902] (js-invoke java.time.Duration "ofSeconds" long26902)))
(clojure.core/defn minus-days {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this26903 ^long long26904] (.minusDays this26903 long26904)))
(clojure.core/defn to-days {:arglists (quote (["java.time.Duration"]))} (^long [^js/JSJoda.Duration this26905] (.toDays this26905)))
