(ns cljc.java-time.duration (:refer-clojure :exclude [get range format min max next name resolve short]) (:require [cljc.java-time.extn.calendar-awareness] [java.time :refer [Duration]]))
(def zero (goog.object/get java.time.Duration "ZERO"))
(clojure.core/defn minus-minutes {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11438 ^long long11439] (.minusMinutes this11438 long11439)))
(clojure.core/defn to-nanos {:arglists (quote (["java.time.Duration"]))} (^long [^js/JSJoda.Duration this11440] (.toNanos this11440)))
(clojure.core/defn minus-millis {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11441 ^long long11442] (.minusMillis this11441 long11442)))
(clojure.core/defn minus-hours {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11443 ^long long11444] (.minusHours this11443 long11444)))
(clojure.core/defn of-days {:arglists (quote (["long"]))} (^js/JSJoda.Duration [^long long11445] (js-invoke java.time.Duration "ofDays" long11445)))
(clojure.core/defn is-negative {:arglists (quote (["java.time.Duration"]))} (^boolean [^js/JSJoda.Duration this11446] (.isNegative this11446)))
(clojure.core/defn of {:arglists (quote (["long" "java.time.temporal.TemporalUnit"]))} (^js/JSJoda.Duration [^long long11447 ^js/JSJoda.TemporalUnit java-time-temporal-TemporalUnit11448] (js-invoke java.time.Duration "of" long11447 java-time-temporal-TemporalUnit11448)))
(clojure.core/defn is-zero {:arglists (quote (["java.time.Duration"]))} (^boolean [^js/JSJoda.Duration this11449] (.isZero this11449)))
(clojure.core/defn multiplied-by {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11450 ^long long11451] (.multipliedBy this11450 long11451)))
(clojure.core/defn with-nanos {:arglists (quote (["java.time.Duration" "int"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11452 ^int int11453] (.withNanos this11452 int11453)))
(clojure.core/defn get-units {:arglists (quote (["java.time.Duration"]))} (^java.util.List [^js/JSJoda.Duration this11454] (.units this11454)))
(clojure.core/defn get-nano {:arglists (quote (["java.time.Duration"]))} (^int [^js/JSJoda.Duration this11455] (.nano this11455)))
(clojure.core/defn plus-millis {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11456 ^long long11457] (.plusMillis this11456 long11457)))
(clojure.core/defn to-minutes {:arglists (quote (["java.time.Duration"]))} (^long [^js/JSJoda.Duration this11458] (.toMinutes this11458)))
(clojure.core/defn minus-seconds {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11459 ^long long11460] (.minusSeconds this11459 long11460)))
(clojure.core/defn plus-nanos {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11461 ^long long11462] (.plusNanos this11461 long11462)))
(clojure.core/defn plus {:arglists (quote (["java.time.Duration" "java.time.Duration"] ["java.time.Duration" "long" "java.time.temporal.TemporalUnit"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11463 ^js/JSJoda.Duration java-time-Duration11464] (.plus this11463 java-time-Duration11464)) (^js/JSJoda.Duration [^js/JSJoda.Duration this11465 ^long long11466 ^js/JSJoda.TemporalUnit java-time-temporal-TemporalUnit11467] (.plus this11465 long11466 java-time-temporal-TemporalUnit11467)))
(clojure.core/defn divided-by {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11468 ^long long11469] (.dividedBy this11468 long11469)))
(clojure.core/defn plus-minutes {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11470 ^long long11471] (.plusMinutes this11470 long11471)))
(clojure.core/defn to-string {:arglists (quote (["java.time.Duration"]))} (^java.lang.String [^js/JSJoda.Duration this11472] (.toString this11472)))
(clojure.core/defn minus {:arglists (quote (["java.time.Duration" "java.time.Duration"] ["java.time.Duration" "long" "java.time.temporal.TemporalUnit"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11473 ^js/JSJoda.Duration java-time-Duration11474] (.minus this11473 java-time-Duration11474)) (^js/JSJoda.Duration [^js/JSJoda.Duration this11475 ^long long11476 ^js/JSJoda.TemporalUnit java-time-temporal-TemporalUnit11477] (.minus this11475 long11476 java-time-temporal-TemporalUnit11477)))
(clojure.core/defn add-to {:arglists (quote (["java.time.Duration" "java.time.temporal.Temporal"]))} (^js/JSJoda.Temporal [^js/JSJoda.Duration this11478 ^js/JSJoda.Temporal java-time-temporal-Temporal11479] (.addTo this11478 java-time-temporal-Temporal11479)))
(clojure.core/defn plus-hours {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11480 ^long long11481] (.plusHours this11480 long11481)))
(clojure.core/defn plus-days {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11482 ^long long11483] (.plusDays this11482 long11483)))
(clojure.core/defn of-hours {:arglists (quote (["long"]))} (^js/JSJoda.Duration [^long long11484] (js-invoke java.time.Duration "ofHours" long11484)))
(clojure.core/defn to-millis {:arglists (quote (["java.time.Duration"]))} (^long [^js/JSJoda.Duration this11485] (.toMillis this11485)))
(clojure.core/defn to-hours {:arglists (quote (["java.time.Duration"]))} (^long [^js/JSJoda.Duration this11486] (.toHours this11486)))
(clojure.core/defn of-nanos {:arglists (quote (["long"]))} (^js/JSJoda.Duration [^long long11487] (js-invoke java.time.Duration "ofNanos" long11487)))
(clojure.core/defn of-millis {:arglists (quote (["long"]))} (^js/JSJoda.Duration [^long long11488] (js-invoke java.time.Duration "ofMillis" long11488)))
(clojure.core/defn negated {:arglists (quote (["java.time.Duration"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11489] (.negated this11489)))
(clojure.core/defn abs {:arglists (quote (["java.time.Duration"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11490] (.abs this11490)))
(clojure.core/defn between {:arglists (quote (["java.time.temporal.Temporal" "java.time.temporal.Temporal"]))} (^js/JSJoda.Duration [^js/JSJoda.Temporal java-time-temporal-Temporal11491 ^js/JSJoda.Temporal java-time-temporal-Temporal11492] (js-invoke java.time.Duration "between" java-time-temporal-Temporal11491 java-time-temporal-Temporal11492)))
(clojure.core/defn get-seconds {:arglists (quote (["java.time.Duration"]))} (^long [^js/JSJoda.Duration this11493] (.seconds this11493)))
(clojure.core/defn from {:arglists (quote (["java.time.temporal.TemporalAmount"]))} (^js/JSJoda.Duration [^js/JSJoda.TemporalAmount java-time-temporal-TemporalAmount11494] (js-invoke java.time.Duration "from" java-time-temporal-TemporalAmount11494)))
(clojure.core/defn minus-nanos {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11495 ^long long11496] (.minusNanos this11495 long11496)))
(clojure.core/defn parse {:arglists (quote (["java.lang.CharSequence"]))} (^js/JSJoda.Duration [^java.lang.CharSequence java-lang-CharSequence11497] (js-invoke java.time.Duration "parse" java-lang-CharSequence11497)))
(clojure.core/defn hash-code {:arglists (quote (["java.time.Duration"]))} (^int [^js/JSJoda.Duration this11498] (.hashCode this11498)))
(clojure.core/defn with-seconds {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11499 ^long long11500] (.withSeconds this11499 long11500)))
(clojure.core/defn of-minutes {:arglists (quote (["long"]))} (^js/JSJoda.Duration [^long long11501] (js-invoke java.time.Duration "ofMinutes" long11501)))
(clojure.core/defn subtract-from {:arglists (quote (["java.time.Duration" "java.time.temporal.Temporal"]))} (^js/JSJoda.Temporal [^js/JSJoda.Duration this11502 ^js/JSJoda.Temporal java-time-temporal-Temporal11503] (.subtractFrom this11502 java-time-temporal-Temporal11503)))
(clojure.core/defn compare-to {:arglists (quote (["java.time.Duration" "java.time.Duration"] ["java.time.Duration" "java.lang.Object"]))} (^int [this11504 G__11505] (.compareTo ^js/JSJoda.Duration this11504 G__11505)))
(clojure.core/defn plus-seconds {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11506 ^long long11507] (.plusSeconds this11506 long11507)))
(clojure.core/defn get {:arglists (quote (["java.time.Duration" "java.time.temporal.TemporalUnit"]))} (^long [^js/JSJoda.Duration this11508 ^js/JSJoda.TemporalUnit java-time-temporal-TemporalUnit11509] (.get this11508 java-time-temporal-TemporalUnit11509)))
(clojure.core/defn equals {:arglists (quote (["java.time.Duration" "java.lang.Object"]))} (^boolean [^js/JSJoda.Duration this11510 ^java.lang.Object java-lang-Object11511] (.equals this11510 java-lang-Object11511)))
(clojure.core/defn of-seconds {:arglists (quote (["long"] ["long" "long"]))} (^js/JSJoda.Duration [^long long11512] (js-invoke java.time.Duration "ofSeconds" long11512)) (^js/JSJoda.Duration [^long long11513 ^long long11514] (js-invoke java.time.Duration "ofSeconds" long11513 long11514)))
(clojure.core/defn minus-days {:arglists (quote (["java.time.Duration" "long"]))} (^js/JSJoda.Duration [^js/JSJoda.Duration this11515 ^long long11516] (.minusDays this11515 long11516)))
(clojure.core/defn to-days {:arglists (quote (["java.time.Duration"]))} (^long [^js/JSJoda.Duration this11517] (.toDays this11517)))
