(ns cljc.java-time.month (:refer-clojure :exclude [get range format min max next name resolve short]) (:require [cljc.java-time.extn.calendar-awareness] [java.time :refer [Month]]))
(def may (goog.object/get java.time.Month "MAY"))
(def december (goog.object/get java.time.Month "DECEMBER"))
(def june (goog.object/get java.time.Month "JUNE"))
(def september (goog.object/get java.time.Month "SEPTEMBER"))
(def february (goog.object/get java.time.Month "FEBRUARY"))
(def january (goog.object/get java.time.Month "JANUARY"))
(def november (goog.object/get java.time.Month "NOVEMBER"))
(def august (goog.object/get java.time.Month "AUGUST"))
(def july (goog.object/get java.time.Month "JULY"))
(def march (goog.object/get java.time.Month "MARCH"))
(def october (goog.object/get java.time.Month "OCTOBER"))
(def april (goog.object/get java.time.Month "APRIL"))
(clojure.core/defn range {:arglists (quote (["java.time.Month" "java.time.temporal.TemporalField"]))} (^js/JSJoda.ValueRange [^js/JSJoda.Month this11225 ^js/JSJoda.TemporalField java-time-temporal-TemporalField11226] (.range this11225 java-time-temporal-TemporalField11226)))
(clojure.core/defn values {:arglists (quote ([]))} (^"java.lang.Class" [] (js-invoke java.time.Month "values")))
(clojure.core/defn value-of {:arglists (quote (["java.lang.String"] ["java.lang.Class" "java.lang.String"]))} (^js/JSJoda.Month [^java.lang.String java-lang-String11227] (js-invoke java.time.Month "valueOf" java-lang-String11227)) (^java.lang.Enum [^java.lang.Class java-lang-Class11228 ^java.lang.String java-lang-String11229] (js-invoke java.time.Month "valueOf" java-lang-Class11228 java-lang-String11229)))
(clojure.core/defn of {:arglists (quote (["int"]))} (^js/JSJoda.Month [^int int11230] (js-invoke java.time.Month "of" int11230)))
(clojure.core/defn ordinal {:arglists (quote (["java.time.Month"]))} (^int [^js/JSJoda.Month this11231] (.ordinal this11231)))
(clojure.core/defn first-month-of-quarter {:arglists (quote (["java.time.Month"]))} (^js/JSJoda.Month [^js/JSJoda.Month this11232] (.firstMonthOfQuarter this11232)))
(clojure.core/defn min-length {:arglists (quote (["java.time.Month"]))} (^int [^js/JSJoda.Month this11233] (.minLength this11233)))
(clojure.core/defn plus {:arglists (quote (["java.time.Month" "long"]))} (^js/JSJoda.Month [^js/JSJoda.Month this11234 ^long long11235] (.plus this11234 long11235)))
(clojure.core/defn query {:arglists (quote (["java.time.Month" "java.time.temporal.TemporalQuery"]))} (^java.lang.Object [^js/JSJoda.Month this11236 ^js/JSJoda.TemporalQuery java-time-temporal-TemporalQuery11237] (.query this11236 java-time-temporal-TemporalQuery11237)))
(clojure.core/defn to-string {:arglists (quote (["java.time.Month"]))} (^java.lang.String [^js/JSJoda.Month this11238] (.toString this11238)))
(clojure.core/defn first-day-of-year {:arglists (quote (["java.time.Month" "boolean"]))} (^int [^js/JSJoda.Month this11239 ^boolean boolean11240] (.firstDayOfYear this11239 boolean11240)))
(clojure.core/defn minus {:arglists (quote (["java.time.Month" "long"]))} (^js/JSJoda.Month [^js/JSJoda.Month this11241 ^long long11242] (.minus this11241 long11242)))
(clojure.core/defn get-display-name {:arglists (quote (["java.time.Month" "java.time.format.TextStyle" "java.util.Locale"]))} (^java.lang.String [^js/JSJoda.Month this11243 ^js/JSJoda.TextStyle java-time-format-TextStyle11244 ^java.util.Locale java-util-Locale11245] (.displayName this11243 java-time-format-TextStyle11244 java-util-Locale11245)))
(clojure.core/defn get-value {:arglists (quote (["java.time.Month"]))} (^int [^js/JSJoda.Month this11246] (.value this11246)))
(clojure.core/defn max-length {:arglists (quote (["java.time.Month"]))} (^int [^js/JSJoda.Month this11247] (.maxLength this11247)))
(clojure.core/defn name {:arglists (quote (["java.time.Month"]))} (^java.lang.String [^js/JSJoda.Month this11248] (.name this11248)))
(clojure.core/defn get-long {:arglists (quote (["java.time.Month" "java.time.temporal.TemporalField"]))} (^long [^js/JSJoda.Month this11249 ^js/JSJoda.TemporalField java-time-temporal-TemporalField11250] (.getLong this11249 java-time-temporal-TemporalField11250)))
(clojure.core/defn length {:arglists (quote (["java.time.Month" "boolean"]))} (^int [^js/JSJoda.Month this11251 ^boolean boolean11252] (.length this11251 boolean11252)))
(clojure.core/defn get-declaring-class {:arglists (quote (["java.time.Month"]))} (^java.lang.Class [^js/JSJoda.Month this11253] (.declaringClass this11253)))
(clojure.core/defn from {:arglists (quote (["java.time.temporal.TemporalAccessor"]))} (^js/JSJoda.Month [^js/JSJoda.TemporalAccessor java-time-temporal-TemporalAccessor11254] (js-invoke java.time.Month "from" java-time-temporal-TemporalAccessor11254)))
(clojure.core/defn is-supported {:arglists (quote (["java.time.Month" "java.time.temporal.TemporalField"]))} (^boolean [^js/JSJoda.Month this11255 ^js/JSJoda.TemporalField java-time-temporal-TemporalField11256] (.isSupported this11255 java-time-temporal-TemporalField11256)))
(clojure.core/defn hash-code {:arglists (quote (["java.time.Month"]))} (^int [^js/JSJoda.Month this11257] (.hashCode this11257)))
(clojure.core/defn adjust-into {:arglists (quote (["java.time.Month" "java.time.temporal.Temporal"]))} (^js/JSJoda.Temporal [^js/JSJoda.Month this11258 ^js/JSJoda.Temporal java-time-temporal-Temporal11259] (.adjustInto this11258 java-time-temporal-Temporal11259)))
(clojure.core/defn compare-to {:arglists (quote (["java.time.Month" "java.lang.Object"] ["java.time.Month" "java.lang.Enum"]))} (^int [this11260 G__11261] (.compareTo ^js/JSJoda.Month this11260 G__11261)))
(clojure.core/defn get {:arglists (quote (["java.time.Month" "java.time.temporal.TemporalField"]))} (^int [^js/JSJoda.Month this11262 ^js/JSJoda.TemporalField java-time-temporal-TemporalField11263] (.get this11262 java-time-temporal-TemporalField11263)))
(clojure.core/defn equals {:arglists (quote (["java.time.Month" "java.lang.Object"]))} (^boolean [^js/JSJoda.Month this11264 ^java.lang.Object java-lang-Object11265] (.equals this11264 java-lang-Object11265)))
