(ns cljc.java-time.month (:refer-clojure :exclude [get range format min max next name resolve short]) (:require [cljc.java-time.extn.calendar-awareness] [java.time :refer [Month]]))
(def may (goog.object/get java.time.Month "MAY"))
(def december (goog.object/get java.time.Month "DECEMBER"))
(def june (goog.object/get java.time.Month "JUNE"))
(def september (goog.object/get java.time.Month "SEPTEMBER"))
(def february (goog.object/get java.time.Month "FEBRUARY"))
(def january (goog.object/get java.time.Month "JANUARY"))
(def november (goog.object/get java.time.Month "NOVEMBER"))
(def august (goog.object/get java.time.Month "AUGUST"))
(def july (goog.object/get java.time.Month "JULY"))
(def march (goog.object/get java.time.Month "MARCH"))
(def october (goog.object/get java.time.Month "OCTOBER"))
(def april (goog.object/get java.time.Month "APRIL"))
(clojure.core/defn range {:arglists (quote (["java.time.Month" "java.time.temporal.TemporalField"]))} (^js/JSJoda.ValueRange [^js/JSJoda.Month this26613 ^js/JSJoda.TemporalField java-time-temporal-TemporalField26614] (.range this26613 java-time-temporal-TemporalField26614)))
(clojure.core/defn values {:arglists (quote ([]))} (^"java.lang.Class" [] (js-invoke java.time.Month "values")))
(clojure.core/defn value-of {:arglists (quote (["java.lang.String"] ["java.lang.Class" "java.lang.String"]))} (^js/JSJoda.Month [^java.lang.String java-lang-String26615] (js-invoke java.time.Month "valueOf" java-lang-String26615)) (^java.lang.Enum [^java.lang.Class java-lang-Class26616 ^java.lang.String java-lang-String26617] (js-invoke java.time.Month "valueOf" java-lang-Class26616 java-lang-String26617)))
(clojure.core/defn of {:arglists (quote (["int"]))} (^js/JSJoda.Month [^int int26618] (js-invoke java.time.Month "of" int26618)))
(clojure.core/defn ordinal {:arglists (quote (["java.time.Month"]))} (^int [^js/JSJoda.Month this26619] (.ordinal this26619)))
(clojure.core/defn first-month-of-quarter {:arglists (quote (["java.time.Month"]))} (^js/JSJoda.Month [^js/JSJoda.Month this26620] (.firstMonthOfQuarter this26620)))
(clojure.core/defn min-length {:arglists (quote (["java.time.Month"]))} (^int [^js/JSJoda.Month this26621] (.minLength this26621)))
(clojure.core/defn plus {:arglists (quote (["java.time.Month" "long"]))} (^js/JSJoda.Month [^js/JSJoda.Month this26622 ^long long26623] (.plus this26622 long26623)))
(clojure.core/defn query {:arglists (quote (["java.time.Month" "java.time.temporal.TemporalQuery"]))} (^java.lang.Object [^js/JSJoda.Month this26624 ^js/JSJoda.TemporalQuery java-time-temporal-TemporalQuery26625] (.query this26624 java-time-temporal-TemporalQuery26625)))
(clojure.core/defn to-string {:arglists (quote (["java.time.Month"]))} (^java.lang.String [^js/JSJoda.Month this26626] (.toString this26626)))
(clojure.core/defn first-day-of-year {:arglists (quote (["java.time.Month" "boolean"]))} (^int [^js/JSJoda.Month this26627 ^boolean boolean26628] (.firstDayOfYear this26627 boolean26628)))
(clojure.core/defn minus {:arglists (quote (["java.time.Month" "long"]))} (^js/JSJoda.Month [^js/JSJoda.Month this26629 ^long long26630] (.minus this26629 long26630)))
(clojure.core/defn get-display-name {:arglists (quote (["java.time.Month" "java.time.format.TextStyle" "java.util.Locale"]))} (^java.lang.String [^js/JSJoda.Month this26631 ^js/JSJoda.TextStyle java-time-format-TextStyle26632 ^java.util.Locale java-util-Locale26633] (.displayName this26631 java-time-format-TextStyle26632 java-util-Locale26633)))
(clojure.core/defn get-value {:arglists (quote (["java.time.Month"]))} (^int [^js/JSJoda.Month this26634] (.value this26634)))
(clojure.core/defn max-length {:arglists (quote (["java.time.Month"]))} (^int [^js/JSJoda.Month this26635] (.maxLength this26635)))
(clojure.core/defn name {:arglists (quote (["java.time.Month"]))} (^java.lang.String [^js/JSJoda.Month this26636] (.name this26636)))
(clojure.core/defn get-long {:arglists (quote (["java.time.Month" "java.time.temporal.TemporalField"]))} (^long [^js/JSJoda.Month this26637 ^js/JSJoda.TemporalField java-time-temporal-TemporalField26638] (.getLong this26637 java-time-temporal-TemporalField26638)))
(clojure.core/defn length {:arglists (quote (["java.time.Month" "boolean"]))} (^int [^js/JSJoda.Month this26639 ^boolean boolean26640] (.length this26639 boolean26640)))
(clojure.core/defn get-declaring-class {:arglists (quote (["java.time.Month"]))} (^java.lang.Class [^js/JSJoda.Month this26641] (.declaringClass this26641)))
(clojure.core/defn from {:arglists (quote (["java.time.temporal.TemporalAccessor"]))} (^js/JSJoda.Month [^js/JSJoda.TemporalAccessor java-time-temporal-TemporalAccessor26642] (js-invoke java.time.Month "from" java-time-temporal-TemporalAccessor26642)))
(clojure.core/defn is-supported {:arglists (quote (["java.time.Month" "java.time.temporal.TemporalField"]))} (^boolean [^js/JSJoda.Month this26643 ^js/JSJoda.TemporalField java-time-temporal-TemporalField26644] (.isSupported this26643 java-time-temporal-TemporalField26644)))
(clojure.core/defn hash-code {:arglists (quote (["java.time.Month"]))} (^int [^js/JSJoda.Month this26645] (.hashCode this26645)))
(clojure.core/defn adjust-into {:arglists (quote (["java.time.Month" "java.time.temporal.Temporal"]))} (^js/JSJoda.Temporal [^js/JSJoda.Month this26646 ^js/JSJoda.Temporal java-time-temporal-Temporal26647] (.adjustInto this26646 java-time-temporal-Temporal26647)))
(clojure.core/defn compare-to {:arglists (quote (["java.time.Month" "java.lang.Enum"]))} (^int [^js/JSJoda.Month this26648 ^java.lang.Enum java-lang-Enum26649] (.compareTo this26648 java-lang-Enum26649)))
(clojure.core/defn get {:arglists (quote (["java.time.Month" "java.time.temporal.TemporalField"]))} (^int [^js/JSJoda.Month this26650 ^js/JSJoda.TemporalField java-time-temporal-TemporalField26651] (.get this26650 java-time-temporal-TemporalField26651)))
(clojure.core/defn equals {:arglists (quote (["java.time.Month" "java.lang.Object"]))} (^boolean [^js/JSJoda.Month this26652 ^java.lang.Object java-lang-Object26653] (.equals this26652 java-lang-Object26653)))
