(ns cljc.java-time.zone-id (:refer-clojure :exclude [get range format min max next name resolve short]) (:require [cljc.java-time.extn.calendar-awareness] [java.time :refer [ZoneId]]))
(def short-ids (goog.object/get java.time.ZoneId "SHORT_IDS"))
(clojure.core/defn get-available-zone-ids {:arglists (quote ([]))} (^java.util.Set [] (js-invoke java.time.ZoneId "getAvailableZoneIds")))
(clojure.core/defn of {:arglists (quote (["java.lang.String" "java.util.Map"] ["java.lang.String"]))} (^js/JSJoda.ZoneId [^java.lang.String java-lang-String26298 ^java.util.Map java-util-Map26299] (js-invoke java.time.ZoneId "of" java-lang-String26298 java-util-Map26299)) (^js/JSJoda.ZoneId [^java.lang.String java-lang-String26300] (js-invoke java.time.ZoneId "of" java-lang-String26300)))
(clojure.core/defn of-offset {:arglists (quote (["java.lang.String" "java.time.ZoneOffset"]))} (^js/JSJoda.ZoneId [^java.lang.String java-lang-String26301 ^js/JSJoda.ZoneOffset java-time-ZoneOffset26302] (js-invoke java.time.ZoneId "ofOffset" java-lang-String26301 java-time-ZoneOffset26302)))
(clojure.core/defn to-string {:arglists (quote (["java.time.ZoneId"]))} (^java.lang.String [^js/JSJoda.ZoneId this26303] (.toString this26303)))
(clojure.core/defn get-display-name {:arglists (quote (["java.time.ZoneId" "java.time.format.TextStyle" "java.util.Locale"]))} (^java.lang.String [^js/JSJoda.ZoneId this26304 ^js/JSJoda.TextStyle java-time-format-TextStyle26305 ^java.util.Locale java-util-Locale26306] (.displayName this26304 java-time-format-TextStyle26305 java-util-Locale26306)))
(clojure.core/defn get-rules {:arglists (quote (["java.time.ZoneId"]))} (^js/JSJoda.ZoneRules [^js/JSJoda.ZoneId this26307] (.rules this26307)))
(clojure.core/defn get-id {:arglists (quote (["java.time.ZoneId"]))} (^java.lang.String [^js/JSJoda.ZoneId this26308] (.id this26308)))
(clojure.core/defn normalized {:arglists (quote (["java.time.ZoneId"]))} (^js/JSJoda.ZoneId [^js/JSJoda.ZoneId this26309] (.normalized this26309)))
(clojure.core/defn system-default {:arglists (quote ([]))} (^js/JSJoda.ZoneId [] (js-invoke java.time.ZoneId "systemDefault")))
(clojure.core/defn from {:arglists (quote (["java.time.temporal.TemporalAccessor"]))} (^js/JSJoda.ZoneId [^js/JSJoda.TemporalAccessor java-time-temporal-TemporalAccessor26310] (js-invoke java.time.ZoneId "from" java-time-temporal-TemporalAccessor26310)))
(clojure.core/defn hash-code {:arglists (quote (["java.time.ZoneId"]))} (^int [^js/JSJoda.ZoneId this26311] (.hashCode this26311)))
(clojure.core/defn equals {:arglists (quote (["java.time.ZoneId" "java.lang.Object"]))} (^boolean [^js/JSJoda.ZoneId this26312 ^java.lang.Object java-lang-Object26313] (.equals this26312 java-lang-Object26313)))
